"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8b432bd0a5f2

from __future__ import annotations
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetTasksScheduledIDRequestTypedDict(TypedDict):
    id: str
    r"""Scheduled Task ID"""


class GetTasksScheduledIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Scheduled Task ID"""
