// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 29b3656a586f

package operations

type DeleteSecretsIntegrationsIDRequest struct {
	// Integration ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteSecretsIntegrationsIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
