// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeletePricesUnitsIDRequest struct {
	// Price unit ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeletePricesUnitsIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
