// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 35ed521843f5

package operations

type DeletePaymentsIDRequest struct {
	// Payment ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeletePaymentsIDRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
