// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetAddonsIDRequest struct {
	// Addon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetAddonsIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
