// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2505394c2363

package operations

type GetCouponsIDRequest struct {
	// Coupon ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetCouponsIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
