// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 66362d632f3b

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type GetCustomersIDRequest struct {
	// Customer ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetCustomersIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetCustomersIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoCustomerResponse *components.DtoCustomerResponse
}

func (g GetCustomersIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomersIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomersIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCustomersIDResponse) GetDtoCustomerResponse() *components.DtoCustomerResponse {
	if g == nil {
		return nil
	}
	return g.DtoCustomerResponse
}
