// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetConnectionsIDRequest struct {
	// Connection ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetConnectionsIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
