// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetCreditnotesIDRequest struct {
	// Credit note ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetCreditnotesIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
