// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetCustomersExternalExternalIDRequest struct {
	// Customer External ID
	ExternalID string `pathParam:"style=simple,explode=false,name=external_id"`
}

func (g *GetCustomersExternalExternalIDRequest) GetExternalID() string {
	if g == nil {
		return ""
	}
	return g.ExternalID
}
