// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8e9a773bf7ad

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type GetFeaturesIDRequest struct {
	// Feature ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetFeaturesIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetFeaturesIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoFeatureResponse *components.DtoFeatureResponse
}

func (g GetFeaturesIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFeaturesIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetFeaturesIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetFeaturesIDResponse) GetDtoFeatureResponse() *components.DtoFeatureResponse {
	if g == nil {
		return nil
	}
	return g.DtoFeatureResponse
}
