// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetGroupsIDRequest struct {
	// Group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetGroupsIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
