// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b06b99e4644a

package operations

type GetPricesIDRequest struct {
	// Price ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPricesIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
