// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetPaymentsIDRequest struct {
	// Payment ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetPaymentsIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}
