// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ad0aeecfe136

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type GetSecretsAPIKeysRequest struct {
	// Limit
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Offset
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
	// Status (published/archived)
	Status *string `queryParam:"style=form,explode=true,name=status"`
}

func (g *GetSecretsAPIKeysRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetSecretsAPIKeysRequest) GetOffset() *int64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetSecretsAPIKeysRequest) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

type GetSecretsAPIKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoListSecretsResponse *components.DtoListSecretsResponse
}

func (g GetSecretsAPIKeysResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSecretsAPIKeysResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSecretsAPIKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSecretsAPIKeysResponse) GetDtoListSecretsResponse() *components.DtoListSecretsResponse {
	if g == nil {
		return nil
	}
	return g.DtoListSecretsResponse
}
