// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a70d10ffcc1d

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type GetTasksIDRequest struct {
	// Task ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetTasksIDRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetTasksIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoTaskResponse *components.DtoTaskResponse
}

func (g GetTasksIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTasksIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTasksIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTasksIDResponse) GetDtoTaskResponse() *components.DtoTaskResponse {
	if g == nil {
		return nil
	}
	return g.DtoTaskResponse
}
