// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2683b1f8a35e

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type PostInvoicesIDFinalizeRequest struct {
	// Invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (p *PostInvoicesIDFinalizeRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

type PostInvoicesIDFinalizeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	GinH map[string]components.GinH
}

func (p PostInvoicesIDFinalizeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostInvoicesIDFinalizeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostInvoicesIDFinalizeResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostInvoicesIDFinalizeResponse) GetGinH() map[string]components.GinH {
	if p == nil {
		return nil
	}
	return p.GinH
}
