// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 113f227512f3

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type PostInvoicesPreviewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoInvoiceResponse *components.DtoInvoiceResponse
}

func (p PostInvoicesPreviewResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostInvoicesPreviewResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostInvoicesPreviewResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostInvoicesPreviewResponse) GetDtoInvoiceResponse() *components.DtoInvoiceResponse {
	if p == nil {
		return nil
	}
	return p.DtoInvoiceResponse
}
