// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 66b491f0d87d

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type PostEntitlementsBulkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoCreateBulkEntitlementResponse *components.DtoCreateBulkEntitlementResponse
}

func (p PostEntitlementsBulkResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostEntitlementsBulkResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostEntitlementsBulkResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostEntitlementsBulkResponse) GetDtoCreateBulkEntitlementResponse() *components.DtoCreateBulkEntitlementResponse {
	if p == nil {
		return nil
	}
	return p.DtoCreateBulkEntitlementResponse
}
