// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 03b80acb3061

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type PostEntitlementsSearchResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoListEntitlementsResponse *components.DtoListEntitlementsResponse
}

func (p PostEntitlementsSearchResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostEntitlementsSearchResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostEntitlementsSearchResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostEntitlementsSearchResponse) GetDtoListEntitlementsResponse() *components.DtoListEntitlementsResponse {
	if p == nil {
		return nil
	}
	return p.DtoListEntitlementsResponse
}
