// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b817058a18f8

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type PostPricesUnitsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoPriceUnitResponse *components.DtoPriceUnitResponse
}

func (p PostPricesUnitsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostPricesUnitsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostPricesUnitsResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostPricesUnitsResponse) GetDtoPriceUnitResponse() *components.DtoPriceUnitResponse {
	if p == nil {
		return nil
	}
	return p.DtoPriceUnitResponse
}
