// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/go-sdk/models/components"
)

type PutPlansIDRequest struct {
	// Plan ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Plan update
	Body components.DtoUpdatePlanRequest `request:"mediaType=application/json"`
}

func (p *PutPlansIDRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutPlansIDRequest) GetBody() components.DtoUpdatePlanRequest {
	if p == nil {
		return components.DtoUpdatePlanRequest{}
	}
	return p.Body
}
