// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/go-sdk/models/components"
)

type PutPaymentsIDRequest struct {
	// Payment ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Payment configuration
	Body components.DtoUpdatePaymentRequest `request:"mediaType=application/json"`
}

func (p *PutPaymentsIDRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutPaymentsIDRequest) GetBody() components.DtoUpdatePaymentRequest {
	if p == nil {
		return components.DtoUpdatePaymentRequest{}
	}
	return p.Body
}
