// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6dc6e173829d

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type PutTenantsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoTenantResponse *components.DtoTenantResponse
}

func (p PutTenantsUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutTenantsUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutTenantsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutTenantsUpdateResponse) GetDtoTenantResponse() *components.DtoTenantResponse {
	if p == nil {
		return nil
	}
	return p.DtoTenantResponse
}
