// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 02f9a6c80eeb

package operations

import (
	"github.com/flexprice/go-sdk/internal/utils"
	"github.com/flexprice/go-sdk/models/components"
)

type PutWalletsIDRequest struct {
	// Wallet ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Update wallet request
	Body components.DtoUpdateWalletRequest `request:"mediaType=application/json"`
}

func (p *PutWalletsIDRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PutWalletsIDRequest) GetBody() components.DtoUpdateWalletRequest {
	if p == nil {
		return components.DtoUpdateWalletRequest{}
	}
	return p.Body
}

type PutWalletsIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoWalletResponse *components.DtoWalletResponse
}

func (p PutWalletsIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PutWalletsIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PutWalletsIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PutWalletsIDResponse) GetDtoWalletResponse() *components.DtoWalletResponse {
	if p == nil {
		return nil
	}
	return p.DtoWalletResponse
}
