// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DtoBillingCycleInfo struct {
	// billing_anchor is the new billing anchor
	BillingAnchor  *string              `json:"billing_anchor,omitzero"`
	BillingCadence *TypesBillingCadence `json:"billing_cadence,omitzero"`
	BillingPeriod  *TypesBillingPeriod  `json:"billing_period,omitzero"`
	// billing_period_count is the billing period count
	BillingPeriodCount *int64 `json:"billing_period_count,omitzero"`
	// period_end is the end of the new billing period
	PeriodEnd *string `json:"period_end,omitzero"`
	// period_start is the start of the new billing period
	PeriodStart *string `json:"period_start,omitzero"`
}

func (d *DtoBillingCycleInfo) GetBillingAnchor() *string {
	if d == nil {
		return nil
	}
	return d.BillingAnchor
}

func (d *DtoBillingCycleInfo) GetBillingCadence() *TypesBillingCadence {
	if d == nil {
		return nil
	}
	return d.BillingCadence
}

func (d *DtoBillingCycleInfo) GetBillingPeriod() *TypesBillingPeriod {
	if d == nil {
		return nil
	}
	return d.BillingPeriod
}

func (d *DtoBillingCycleInfo) GetBillingPeriodCount() *int64 {
	if d == nil {
		return nil
	}
	return d.BillingPeriodCount
}

func (d *DtoBillingCycleInfo) GetPeriodEnd() *string {
	if d == nil {
		return nil
	}
	return d.PeriodEnd
}

func (d *DtoBillingCycleInfo) GetPeriodStart() *string {
	if d == nil {
		return nil
	}
	return d.PeriodStart
}
