// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/go-sdk/internal/utils"
)

type DtoCreateBulkEntitlementResponse struct {
	Items []DtoEntitlementResponse `json:"items,omitzero"`
}

func (d DtoCreateBulkEntitlementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoCreateBulkEntitlementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoCreateBulkEntitlementResponse) GetItems() []DtoEntitlementResponse {
	if d == nil {
		return nil
	}
	return d.Items
}
