// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DtoEntitlementSourceEntityType string

const (
	DtoEntitlementSourceEntityTypePlan         DtoEntitlementSourceEntityType = "plan"
	DtoEntitlementSourceEntityTypeAddon        DtoEntitlementSourceEntityType = "addon"
	DtoEntitlementSourceEntityTypeSubscription DtoEntitlementSourceEntityType = "subscription"
)

func (e DtoEntitlementSourceEntityType) ToPointer() *DtoEntitlementSourceEntityType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *DtoEntitlementSourceEntityType) IsExact() bool {
	if e != nil {
		switch *e {
		case "plan", "addon", "subscription":
			return true
		}
	}
	return false
}
