// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/go-sdk/internal/utils"
)

type DtoGetEventsResponse struct {
	Events       []DtoEvent `json:"events,omitzero"`
	HasMore      *bool      `json:"has_more,omitzero"`
	IterFirstKey *string    `json:"iter_first_key,omitzero"`
	IterLastKey  *string    `json:"iter_last_key,omitzero"`
	Offset       *int64     `json:"offset,omitzero"`
	TotalCount   *int64     `json:"total_count,omitzero"`
}

func (d DtoGetEventsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoGetEventsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoGetEventsResponse) GetEvents() []DtoEvent {
	if d == nil {
		return nil
	}
	return d.Events
}

func (d *DtoGetEventsResponse) GetHasMore() *bool {
	if d == nil {
		return nil
	}
	return d.HasMore
}

func (d *DtoGetEventsResponse) GetIterFirstKey() *string {
	if d == nil {
		return nil
	}
	return d.IterFirstKey
}

func (d *DtoGetEventsResponse) GetIterLastKey() *string {
	if d == nil {
		return nil
	}
	return d.IterLastKey
}

func (d *DtoGetEventsResponse) GetOffset() *int64 {
	if d == nil {
		return nil
	}
	return d.Offset
}

func (d *DtoGetEventsResponse) GetTotalCount() *int64 {
	if d == nil {
		return nil
	}
	return d.TotalCount
}
