// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/go-sdk/internal/utils"
)

type DtoListSecretsResponse struct {
	Items      []DtoSecretResponse      `json:"items,omitzero"`
	Pagination *TypesPaginationResponse `json:"pagination,omitzero"`
}

func (d DtoListSecretsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoListSecretsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoListSecretsResponse) GetItems() []DtoSecretResponse {
	if d == nil {
		return nil
	}
	return d.Items
}

func (d *DtoListSecretsResponse) GetPagination() *TypesPaginationResponse {
	if d == nil {
		return nil
	}
	return d.Pagination
}
