// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/go-sdk/internal/utils"
)

type DtoListWalletTransactionsResponse struct {
	Items      []DtoWalletTransactionResponse `json:"items,omitzero"`
	Pagination *TypesPaginationResponse       `json:"pagination,omitzero"`
}

func (d DtoListWalletTransactionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoListWalletTransactionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoListWalletTransactionsResponse) GetItems() []DtoWalletTransactionResponse {
	if d == nil {
		return nil
	}
	return d.Items
}

func (d *DtoListWalletTransactionsResponse) GetPagination() *TypesPaginationResponse {
	if d == nil {
		return nil
	}
	return d.Pagination
}
