// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DtoProrationDetail struct {
	ChargeAmount   *string `json:"charge_amount,omitzero"`
	CreditAmount   *string `json:"credit_amount,omitzero"`
	Description    *string `json:"description,omitzero"`
	LineItemID     *string `json:"line_item_id,omitzero"`
	OriginalAmount *string `json:"original_amount,omitzero"`
	PlanName       *string `json:"plan_name,omitzero"`
	PriceID        *string `json:"price_id,omitzero"`
	ProrationDays  *int64  `json:"proration_days,omitzero"`
}

func (d *DtoProrationDetail) GetChargeAmount() *string {
	if d == nil {
		return nil
	}
	return d.ChargeAmount
}

func (d *DtoProrationDetail) GetCreditAmount() *string {
	if d == nil {
		return nil
	}
	return d.CreditAmount
}

func (d *DtoProrationDetail) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *DtoProrationDetail) GetLineItemID() *string {
	if d == nil {
		return nil
	}
	return d.LineItemID
}

func (d *DtoProrationDetail) GetOriginalAmount() *string {
	if d == nil {
		return nil
	}
	return d.OriginalAmount
}

func (d *DtoProrationDetail) GetPlanName() *string {
	if d == nil {
		return nil
	}
	return d.PlanName
}

func (d *DtoProrationDetail) GetPriceID() *string {
	if d == nil {
		return nil
	}
	return d.PriceID
}

func (d *DtoProrationDetail) GetProrationDays() *int64 {
	if d == nil {
		return nil
	}
	return d.ProrationDays
}
