// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/go-sdk/internal/utils"
)

type DtoSubscriptionResponse struct {
	// ActivePauseID references the current active pause configuration
	// This will be null if no pause is active or scheduled
	ActivePauseID *string `json:"active_pause_id,omitzero"`
	// BillingAnchor is the reference point that aligns future billing cycle dates.
	// It sets the day of week for week intervals, the day of month for month and year intervals,
	// and the month of year for year intervals. The timestamp is in UTC format.
	BillingAnchor  *string              `json:"billing_anchor,omitzero"`
	BillingCadence *TypesBillingCadence `json:"billing_cadence,omitzero"`
	BillingCycle   *TypesBillingCycle   `json:"billing_cycle,omitzero"`
	BillingPeriod  *TypesBillingPeriod  `json:"billing_period,omitzero"`
	// BillingPeriodCount is the total number units of the billing period.
	BillingPeriodCount *int64 `json:"billing_period_count,omitzero"`
	// CancelAt is the date the subscription will be canceled
	CancelAt *string `json:"cancel_at,omitzero"`
	// CancelAtPeriodEnd is whether the subscription was canceled at the end of the current period
	CancelAtPeriodEnd *bool `json:"cancel_at_period_end,omitzero"`
	// CanceledAt is the date the subscription was canceled
	CancelledAt *string `json:"cancelled_at,omitzero"`
	// CollectionMethod determines how invoices are collected
	CollectionMethod *string `json:"collection_method,omitzero"`
	// CommitmentAmount is the minimum amount a customer commits to paying for a billing period
	CommitmentAmount *string `json:"commitment_amount,omitzero"`
	// CouponAssociations are the coupon associations for this subscription
	CouponAssociations []DtoCouponAssociationResponse `json:"coupon_associations,omitzero"`
	CreatedAt          *string                        `json:"created_at,omitzero"`
	CreatedBy          *string                        `json:"created_by,omitzero"`
	// Credit grants are the credit grants for this subscription
	CreditGrants []DtoCreditGrantResponse `json:"credit_grants,omitzero"`
	// Currency is the currency of the subscription in lowercase 3 digit ISO codes
	Currency *string `json:"currency,omitzero"`
	// CurrentPeriodEnd is the end of the current period that the subscription has been invoiced for.
	// At the end of this period, a new invoice will be created.
	CurrentPeriodEnd *string `json:"current_period_end,omitzero"`
	// CurrentPeriodStart is the end of the current period that the subscription has been invoiced for.
	// At the end of this period, a new invoice will be created.
	CurrentPeriodStart *string `json:"current_period_start,omitzero"`
	// Customer response object containing all customer information
	Customer *DtoCustomerResponse `json:"customer,omitzero"`
	// CustomerID is the identifier for the customer in our system
	CustomerID       *string `json:"customer_id,omitzero"`
	CustomerTimezone *string `json:"customer_timezone,omitzero"`
	EnableTrueUp     *bool   `json:"enable_true_up,omitzero"`
	// EndDate is the end date of the subscription
	EndDate *string `json:"end_date,omitzero"`
	// EnvironmentID is the environment identifier for the subscription
	EnvironmentID *string `json:"environment_id,omitzero"`
	// GatewayPaymentMethodID is the gateway payment method ID for this subscription
	GatewayPaymentMethodID *string `json:"gateway_payment_method_id,omitzero"`
	// ID is the unique identifier for the subscription
	ID *string `json:"id,omitzero"`
	// InvoicingCustomerID is the customer ID to use for invoicing
	// This can differ from the subscription customer (e.g., parent company invoicing for child company)
	InvoicingCustomerID *string                            `json:"invoicing_customer_id,omitzero"`
	LatestInvoice       *DtoInvoiceResponse                `json:"latest_invoice,omitzero"`
	LineItems           []SubscriptionSubscriptionLineItem `json:"line_items,omitzero"`
	// LookupKey is the key used to lookup the subscription in our system
	LookupKey *string           `json:"lookup_key,omitzero"`
	Metadata  map[string]string `json:"metadata,omitzero"`
	// OverageFactor is a multiplier applied to usage beyond the commitment amount
	OverageFactor *string                         `json:"overage_factor,omitzero"`
	PauseStatus   *TypesPauseStatus               `json:"pause_status,omitzero"`
	Pauses        []SubscriptionSubscriptionPause `json:"pauses,omitzero"`
	// PaymentBehavior determines how subscription payments are handled
	PaymentBehavior *string `json:"payment_behavior,omitzero"`
	// Phases are the subscription phases for this subscription
	Phases []DtoSubscriptionPhaseResponse `json:"phases,omitzero"`
	Plan   *DtoPlanResponse               `json:"plan,omitzero"`
	// PlanID is the identifier for the plan in our system
	PlanID            *string                 `json:"plan_id,omitzero"`
	ProrationBehavior *TypesProrationBehavior `json:"proration_behavior,omitzero"`
	// StartDate is the start date of the subscription
	StartDate          *string                  `json:"start_date,omitzero"`
	Status             *TypesStatus             `json:"status,omitzero"`
	SubscriptionStatus *TypesSubscriptionStatus `json:"subscription_status,omitzero"`
	TenantID           *string                  `json:"tenant_id,omitzero"`
	// TrialEnd is the end date of the trial period
	TrialEnd *string `json:"trial_end,omitzero"`
	// TrialStart is the start date of the trial period
	TrialStart *string `json:"trial_start,omitzero"`
	UpdatedAt  *string `json:"updated_at,omitzero"`
	UpdatedBy  *string `json:"updated_by,omitzero"`
	// Version is used for optimistic locking
	Version *int64 `json:"version,omitzero"`
}

func (d DtoSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoSubscriptionResponse) GetActivePauseID() *string {
	if d == nil {
		return nil
	}
	return d.ActivePauseID
}

func (d *DtoSubscriptionResponse) GetBillingAnchor() *string {
	if d == nil {
		return nil
	}
	return d.BillingAnchor
}

func (d *DtoSubscriptionResponse) GetBillingCadence() *TypesBillingCadence {
	if d == nil {
		return nil
	}
	return d.BillingCadence
}

func (d *DtoSubscriptionResponse) GetBillingCycle() *TypesBillingCycle {
	if d == nil {
		return nil
	}
	return d.BillingCycle
}

func (d *DtoSubscriptionResponse) GetBillingPeriod() *TypesBillingPeriod {
	if d == nil {
		return nil
	}
	return d.BillingPeriod
}

func (d *DtoSubscriptionResponse) GetBillingPeriodCount() *int64 {
	if d == nil {
		return nil
	}
	return d.BillingPeriodCount
}

func (d *DtoSubscriptionResponse) GetCancelAt() *string {
	if d == nil {
		return nil
	}
	return d.CancelAt
}

func (d *DtoSubscriptionResponse) GetCancelAtPeriodEnd() *bool {
	if d == nil {
		return nil
	}
	return d.CancelAtPeriodEnd
}

func (d *DtoSubscriptionResponse) GetCancelledAt() *string {
	if d == nil {
		return nil
	}
	return d.CancelledAt
}

func (d *DtoSubscriptionResponse) GetCollectionMethod() *string {
	if d == nil {
		return nil
	}
	return d.CollectionMethod
}

func (d *DtoSubscriptionResponse) GetCommitmentAmount() *string {
	if d == nil {
		return nil
	}
	return d.CommitmentAmount
}

func (d *DtoSubscriptionResponse) GetCouponAssociations() []DtoCouponAssociationResponse {
	if d == nil {
		return nil
	}
	return d.CouponAssociations
}

func (d *DtoSubscriptionResponse) GetCreatedAt() *string {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *DtoSubscriptionResponse) GetCreatedBy() *string {
	if d == nil {
		return nil
	}
	return d.CreatedBy
}

func (d *DtoSubscriptionResponse) GetCreditGrants() []DtoCreditGrantResponse {
	if d == nil {
		return nil
	}
	return d.CreditGrants
}

func (d *DtoSubscriptionResponse) GetCurrency() *string {
	if d == nil {
		return nil
	}
	return d.Currency
}

func (d *DtoSubscriptionResponse) GetCurrentPeriodEnd() *string {
	if d == nil {
		return nil
	}
	return d.CurrentPeriodEnd
}

func (d *DtoSubscriptionResponse) GetCurrentPeriodStart() *string {
	if d == nil {
		return nil
	}
	return d.CurrentPeriodStart
}

func (d *DtoSubscriptionResponse) GetCustomer() *DtoCustomerResponse {
	if d == nil {
		return nil
	}
	return d.Customer
}

func (d *DtoSubscriptionResponse) GetCustomerID() *string {
	if d == nil {
		return nil
	}
	return d.CustomerID
}

func (d *DtoSubscriptionResponse) GetCustomerTimezone() *string {
	if d == nil {
		return nil
	}
	return d.CustomerTimezone
}

func (d *DtoSubscriptionResponse) GetEnableTrueUp() *bool {
	if d == nil {
		return nil
	}
	return d.EnableTrueUp
}

func (d *DtoSubscriptionResponse) GetEndDate() *string {
	if d == nil {
		return nil
	}
	return d.EndDate
}

func (d *DtoSubscriptionResponse) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DtoSubscriptionResponse) GetGatewayPaymentMethodID() *string {
	if d == nil {
		return nil
	}
	return d.GatewayPaymentMethodID
}

func (d *DtoSubscriptionResponse) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DtoSubscriptionResponse) GetInvoicingCustomerID() *string {
	if d == nil {
		return nil
	}
	return d.InvoicingCustomerID
}

func (d *DtoSubscriptionResponse) GetLatestInvoice() *DtoInvoiceResponse {
	if d == nil {
		return nil
	}
	return d.LatestInvoice
}

func (d *DtoSubscriptionResponse) GetLineItems() []SubscriptionSubscriptionLineItem {
	if d == nil {
		return nil
	}
	return d.LineItems
}

func (d *DtoSubscriptionResponse) GetLookupKey() *string {
	if d == nil {
		return nil
	}
	return d.LookupKey
}

func (d *DtoSubscriptionResponse) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DtoSubscriptionResponse) GetOverageFactor() *string {
	if d == nil {
		return nil
	}
	return d.OverageFactor
}

func (d *DtoSubscriptionResponse) GetPauseStatus() *TypesPauseStatus {
	if d == nil {
		return nil
	}
	return d.PauseStatus
}

func (d *DtoSubscriptionResponse) GetPauses() []SubscriptionSubscriptionPause {
	if d == nil {
		return nil
	}
	return d.Pauses
}

func (d *DtoSubscriptionResponse) GetPaymentBehavior() *string {
	if d == nil {
		return nil
	}
	return d.PaymentBehavior
}

func (d *DtoSubscriptionResponse) GetPhases() []DtoSubscriptionPhaseResponse {
	if d == nil {
		return nil
	}
	return d.Phases
}

func (d *DtoSubscriptionResponse) GetPlan() *DtoPlanResponse {
	if d == nil {
		return nil
	}
	return d.Plan
}

func (d *DtoSubscriptionResponse) GetPlanID() *string {
	if d == nil {
		return nil
	}
	return d.PlanID
}

func (d *DtoSubscriptionResponse) GetProrationBehavior() *TypesProrationBehavior {
	if d == nil {
		return nil
	}
	return d.ProrationBehavior
}

func (d *DtoSubscriptionResponse) GetStartDate() *string {
	if d == nil {
		return nil
	}
	return d.StartDate
}

func (d *DtoSubscriptionResponse) GetStatus() *TypesStatus {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DtoSubscriptionResponse) GetSubscriptionStatus() *TypesSubscriptionStatus {
	if d == nil {
		return nil
	}
	return d.SubscriptionStatus
}

func (d *DtoSubscriptionResponse) GetTenantID() *string {
	if d == nil {
		return nil
	}
	return d.TenantID
}

func (d *DtoSubscriptionResponse) GetTrialEnd() *string {
	if d == nil {
		return nil
	}
	return d.TrialEnd
}

func (d *DtoSubscriptionResponse) GetTrialStart() *string {
	if d == nil {
		return nil
	}
	return d.TrialStart
}

func (d *DtoSubscriptionResponse) GetUpdatedAt() *string {
	if d == nil {
		return nil
	}
	return d.UpdatedAt
}

func (d *DtoSubscriptionResponse) GetUpdatedBy() *string {
	if d == nil {
		return nil
	}
	return d.UpdatedBy
}

func (d *DtoSubscriptionResponse) GetVersion() *int64 {
	if d == nil {
		return nil
	}
	return d.Version
}
