// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/go-sdk/internal/utils"
)

type DtoSubscriptionPhaseResponse struct {
	CreatedAt *string `json:"created_at,omitzero"`
	CreatedBy *string `json:"created_by,omitzero"`
	// EndDate is when the phase ends (nil if phase is still active or indefinite)
	EndDate *string `json:"end_date,omitzero"`
	// EnvironmentID is the environment identifier for the phase
	EnvironmentID *string `json:"environment_id,omitzero"`
	// ID is the unique identifier for the subscription phase
	ID       *string           `json:"id,omitzero"`
	Metadata map[string]string `json:"metadata,omitzero"`
	// StartDate is when the phase starts
	StartDate *string      `json:"start_date,omitzero"`
	Status    *TypesStatus `json:"status,omitzero"`
	// SubscriptionID is the identifier for the subscription
	SubscriptionID *string `json:"subscription_id,omitzero"`
	TenantID       *string `json:"tenant_id,omitzero"`
	UpdatedAt      *string `json:"updated_at,omitzero"`
	UpdatedBy      *string `json:"updated_by,omitzero"`
}

func (d DtoSubscriptionPhaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DtoSubscriptionPhaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DtoSubscriptionPhaseResponse) GetCreatedAt() *string {
	if d == nil {
		return nil
	}
	return d.CreatedAt
}

func (d *DtoSubscriptionPhaseResponse) GetCreatedBy() *string {
	if d == nil {
		return nil
	}
	return d.CreatedBy
}

func (d *DtoSubscriptionPhaseResponse) GetEndDate() *string {
	if d == nil {
		return nil
	}
	return d.EndDate
}

func (d *DtoSubscriptionPhaseResponse) GetEnvironmentID() *string {
	if d == nil {
		return nil
	}
	return d.EnvironmentID
}

func (d *DtoSubscriptionPhaseResponse) GetID() *string {
	if d == nil {
		return nil
	}
	return d.ID
}

func (d *DtoSubscriptionPhaseResponse) GetMetadata() map[string]string {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DtoSubscriptionPhaseResponse) GetStartDate() *string {
	if d == nil {
		return nil
	}
	return d.StartDate
}

func (d *DtoSubscriptionPhaseResponse) GetStatus() *TypesStatus {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DtoSubscriptionPhaseResponse) GetSubscriptionID() *string {
	if d == nil {
		return nil
	}
	return d.SubscriptionID
}

func (d *DtoSubscriptionPhaseResponse) GetTenantID() *string {
	if d == nil {
		return nil
	}
	return d.TenantID
}

func (d *DtoSubscriptionPhaseResponse) GetUpdatedAt() *string {
	if d == nil {
		return nil
	}
	return d.UpdatedAt
}

func (d *DtoSubscriptionPhaseResponse) GetUpdatedBy() *string {
	if d == nil {
		return nil
	}
	return d.UpdatedBy
}
