// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c04d656c979a

package components

type DtoUpdateScheduledTaskRequest struct {
	Enabled bool `json:"enabled"`
}

func (d *DtoUpdateScheduledTaskRequest) GetEnabled() bool {
	if d == nil {
		return false
	}
	return d.Enabled
}
