// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3ba20bbbecab

package components

import (
	"encoding/json"
	"fmt"
)

type TypesSubscriptionStatus string

const (
	TypesSubscriptionStatusActive            TypesSubscriptionStatus = "active"
	TypesSubscriptionStatusPaused            TypesSubscriptionStatus = "paused"
	TypesSubscriptionStatusCancelled         TypesSubscriptionStatus = "cancelled"
	TypesSubscriptionStatusIncomplete        TypesSubscriptionStatus = "incomplete"
	TypesSubscriptionStatusIncompleteExpired TypesSubscriptionStatus = "incomplete_expired"
	TypesSubscriptionStatusPastDue           TypesSubscriptionStatus = "past_due"
	TypesSubscriptionStatusTrialing          TypesSubscriptionStatus = "trialing"
	TypesSubscriptionStatusUnpaid            TypesSubscriptionStatus = "unpaid"
	TypesSubscriptionStatusDraft             TypesSubscriptionStatus = "draft"
)

func (e TypesSubscriptionStatus) ToPointer() *TypesSubscriptionStatus {
	return &e
}
func (e *TypesSubscriptionStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "active":
		fallthrough
	case "paused":
		fallthrough
	case "cancelled":
		fallthrough
	case "incomplete":
		fallthrough
	case "incomplete_expired":
		fallthrough
	case "past_due":
		fallthrough
	case "trialing":
		fallthrough
	case "unpaid":
		fallthrough
	case "draft":
		*e = TypesSubscriptionStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesSubscriptionStatus: %v", v)
	}
}
