// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/flexprice/go-sdk/internal/utils"
)

type TypesWalletConfig struct {
	// AllowedPriceTypes is a list of price types that are allowed for the wallet
	// nil means all price types are allowed
	AllowedPriceTypes []TypesWalletConfigPriceType `json:"allowed_price_types,omitzero"`
}

func (t TypesWalletConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TypesWalletConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TypesWalletConfig) GetAllowedPriceTypes() []TypesWalletConfigPriceType {
	if t == nil {
		return nil
	}
	return t.AllowedPriceTypes
}
