// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesChargebeeConnectionMetadata struct {
	// Chargebee API key (encrypted)
	APIKey *string `json:"api_key,omitzero"`
	// Chargebee site name (not encrypted)
	Site *string `json:"site,omitzero"`
	// Basic Auth password for webhooks (encrypted)
	WebhookPassword *string `json:"webhook_password,omitzero"`
	// Chargebee Webhook Secret (encrypted, optional, NOT USED in v2)
	WebhookSecret *string `json:"webhook_secret,omitzero"`
	// Basic Auth username for webhooks (encrypted)
	WebhookUsername *string `json:"webhook_username,omitzero"`
}

func (t *TypesChargebeeConnectionMetadata) GetAPIKey() *string {
	if t == nil {
		return nil
	}
	return t.APIKey
}

func (t *TypesChargebeeConnectionMetadata) GetSite() *string {
	if t == nil {
		return nil
	}
	return t.Site
}

func (t *TypesChargebeeConnectionMetadata) GetWebhookPassword() *string {
	if t == nil {
		return nil
	}
	return t.WebhookPassword
}

func (t *TypesChargebeeConnectionMetadata) GetWebhookSecret() *string {
	if t == nil {
		return nil
	}
	return t.WebhookSecret
}

func (t *TypesChargebeeConnectionMetadata) GetWebhookUsername() *string {
	if t == nil {
		return nil
	}
	return t.WebhookUsername
}
