// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesCommitmentType string

const (
	TypesCommitmentTypeAmount   TypesCommitmentType = "amount"
	TypesCommitmentTypeQuantity TypesCommitmentType = "quantity"
)

func (e TypesCommitmentType) ToPointer() *TypesCommitmentType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesCommitmentType) IsExact() bool {
	if e != nil {
		switch *e {
		case "amount", "quantity":
			return true
		}
	}
	return false
}
