// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fde88d01acc9

package components

import (
	"encoding/json"
	"fmt"
)

type TypesBillingModel string

const (
	TypesBillingModelFlatFee TypesBillingModel = "FLAT_FEE"
	TypesBillingModelPackage TypesBillingModel = "PACKAGE"
	TypesBillingModelTiered  TypesBillingModel = "TIERED"
)

func (e TypesBillingModel) ToPointer() *TypesBillingModel {
	return &e
}
func (e *TypesBillingModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "FLAT_FEE":
		fallthrough
	case "PACKAGE":
		fallthrough
	case "TIERED":
		*e = TypesBillingModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesBillingModel: %v", v)
	}
}
