// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesPriceUnitType string

const (
	TypesPriceUnitTypeFiat   TypesPriceUnitType = "FIAT"
	TypesPriceUnitTypeCustom TypesPriceUnitType = "CUSTOM"
)

func (e TypesPriceUnitType) ToPointer() *TypesPriceUnitType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesPriceUnitType) IsExact() bool {
	if e != nil {
		switch *e {
		case "FIAT", "CUSTOM":
			return true
		}
	}
	return false
}
