// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/flexprice/go-sdk/internal/utils"
)

type TypesFeatureFilterOrder string

const (
	TypesFeatureFilterOrderAsc  TypesFeatureFilterOrder = "asc"
	TypesFeatureFilterOrderDesc TypesFeatureFilterOrder = "desc"
)

func (e TypesFeatureFilterOrder) ToPointer() *TypesFeatureFilterOrder {
	return &e
}
func (e *TypesFeatureFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = TypesFeatureFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesFeatureFilterOrder: %v", v)
	}
}

type TypesFeatureFilter struct {
	EndTime *string `json:"end_time,omitzero"`
	Expand  *string `json:"expand,omitzero"`
	// Feature specific filters
	FeatureIds []string `json:"feature_ids,omitzero"`
	// filters allows complex filtering based on multiple fields
	Filters      []TypesFilterCondition   `json:"filters,omitzero"`
	Limit        *int64                   `json:"limit,omitzero"`
	LookupKey    *string                  `json:"lookup_key,omitzero"`
	LookupKeys   []string                 `json:"lookup_keys,omitzero"`
	MeterIds     []string                 `json:"meter_ids,omitzero"`
	NameContains *string                  `json:"name_contains,omitzero"`
	Offset       *int64                   `json:"offset,omitzero"`
	Order        *TypesFeatureFilterOrder `json:"order,omitzero"`
	Sort         []TypesSortCondition     `json:"sort,omitzero"`
	StartTime    *string                  `json:"start_time,omitzero"`
	Status       *TypesStatus             `json:"status,omitzero"`
}

func (t TypesFeatureFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TypesFeatureFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TypesFeatureFilter) GetEndTime() *string {
	if t == nil {
		return nil
	}
	return t.EndTime
}

func (t *TypesFeatureFilter) GetExpand() *string {
	if t == nil {
		return nil
	}
	return t.Expand
}

func (t *TypesFeatureFilter) GetFeatureIds() []string {
	if t == nil {
		return nil
	}
	return t.FeatureIds
}

func (t *TypesFeatureFilter) GetFilters() []TypesFilterCondition {
	if t == nil {
		return nil
	}
	return t.Filters
}

func (t *TypesFeatureFilter) GetLimit() *int64 {
	if t == nil {
		return nil
	}
	return t.Limit
}

func (t *TypesFeatureFilter) GetLookupKey() *string {
	if t == nil {
		return nil
	}
	return t.LookupKey
}

func (t *TypesFeatureFilter) GetLookupKeys() []string {
	if t == nil {
		return nil
	}
	return t.LookupKeys
}

func (t *TypesFeatureFilter) GetMeterIds() []string {
	if t == nil {
		return nil
	}
	return t.MeterIds
}

func (t *TypesFeatureFilter) GetNameContains() *string {
	if t == nil {
		return nil
	}
	return t.NameContains
}

func (t *TypesFeatureFilter) GetOffset() *int64 {
	if t == nil {
		return nil
	}
	return t.Offset
}

func (t *TypesFeatureFilter) GetOrder() *TypesFeatureFilterOrder {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *TypesFeatureFilter) GetSort() []TypesSortCondition {
	if t == nil {
		return nil
	}
	return t.Sort
}

func (t *TypesFeatureFilter) GetStartTime() *string {
	if t == nil {
		return nil
	}
	return t.StartTime
}

func (t *TypesFeatureFilter) GetStatus() *TypesStatus {
	if t == nil {
		return nil
	}
	return t.Status
}
