// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesHubSpotConnectionMetadata struct {
	// Private App Access Token (encrypted)
	AccessToken *string `json:"access_token,omitzero"`
	// HubSpot App ID (optional, not encrypted)
	AppID *string `json:"app_id,omitzero"`
	// Private App Client Secret for webhook verification (encrypted)
	ClientSecret *string `json:"client_secret,omitzero"`
}

func (t *TypesHubSpotConnectionMetadata) GetAccessToken() *string {
	if t == nil {
		return nil
	}
	return t.AccessToken
}

func (t *TypesHubSpotConnectionMetadata) GetAppID() *string {
	if t == nil {
		return nil
	}
	return t.AppID
}

func (t *TypesHubSpotConnectionMetadata) GetClientSecret() *string {
	if t == nil {
		return nil
	}
	return t.ClientSecret
}
