// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e9a6682236e3

package components

type TypesTaxRateType string

const (
	TypesTaxRateTypePercentage TypesTaxRateType = "percentage"
	TypesTaxRateTypeFixed      TypesTaxRateType = "fixed"
)

func (e TypesTaxRateType) ToPointer() *TypesTaxRateType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesTaxRateType) IsExact() bool {
	if e != nil {
		switch *e {
		case "percentage", "fixed":
			return true
		}
	}
	return false
}
