// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesCommitmentInfo struct {
	Amount                           *string `json:"amount,omitzero"`
	ComputedCommitmentUtilizedAmount *string `json:"computed_commitment_utilized_amount,omitzero"`
	ComputedOverageAmount            *string `json:"computed_overage_amount,omitzero"`
	// total_cost = computed_commitment_utilized_amount + computed_overage_amount + computed_true_up_amount
	ComputedTrueUpAmount *string `json:"computed_true_up_amount,omitzero"`
	IsWindowed           *bool   `json:"is_windowed,omitzero"`
	OverageFactor        *string `json:"overage_factor,omitzero"`
	// Only used for quantity-based commitments
	Quantity      *string              `json:"quantity,omitzero"`
	TrueUpEnabled *bool                `json:"true_up_enabled,omitzero"`
	Type          *TypesCommitmentType `json:"type,omitzero"`
}

func (t *TypesCommitmentInfo) GetAmount() *string {
	if t == nil {
		return nil
	}
	return t.Amount
}

func (t *TypesCommitmentInfo) GetComputedCommitmentUtilizedAmount() *string {
	if t == nil {
		return nil
	}
	return t.ComputedCommitmentUtilizedAmount
}

func (t *TypesCommitmentInfo) GetComputedOverageAmount() *string {
	if t == nil {
		return nil
	}
	return t.ComputedOverageAmount
}

func (t *TypesCommitmentInfo) GetComputedTrueUpAmount() *string {
	if t == nil {
		return nil
	}
	return t.ComputedTrueUpAmount
}

func (t *TypesCommitmentInfo) GetIsWindowed() *bool {
	if t == nil {
		return nil
	}
	return t.IsWindowed
}

func (t *TypesCommitmentInfo) GetOverageFactor() *string {
	if t == nil {
		return nil
	}
	return t.OverageFactor
}

func (t *TypesCommitmentInfo) GetQuantity() *string {
	if t == nil {
		return nil
	}
	return t.Quantity
}

func (t *TypesCommitmentInfo) GetTrueUpEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.TrueUpEnabled
}

func (t *TypesCommitmentInfo) GetType() *TypesCommitmentType {
	if t == nil {
		return nil
	}
	return t.Type
}
