// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f0bc80e31827

package components

import (
	"encoding/json"
	"fmt"
)

type TypesApplicationStatus string

const (
	TypesApplicationStatusApplied   TypesApplicationStatus = "applied"
	TypesApplicationStatusFailed    TypesApplicationStatus = "failed"
	TypesApplicationStatusPending   TypesApplicationStatus = "pending"
	TypesApplicationStatusSkipped   TypesApplicationStatus = "skipped"
	TypesApplicationStatusCancelled TypesApplicationStatus = "cancelled"
)

func (e TypesApplicationStatus) ToPointer() *TypesApplicationStatus {
	return &e
}
func (e *TypesApplicationStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "applied":
		fallthrough
	case "failed":
		fallthrough
	case "pending":
		fallthrough
	case "skipped":
		fallthrough
	case "cancelled":
		*e = TypesApplicationStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesApplicationStatus: %v", v)
	}
}
