// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesAlertState string

const (
	TypesAlertStateOk      TypesAlertState = "ok"
	TypesAlertStateInfo    TypesAlertState = "info"
	TypesAlertStateWarning TypesAlertState = "warning"
	TypesAlertStateInAlarm TypesAlertState = "in_alarm"
)

func (e TypesAlertState) ToPointer() *TypesAlertState {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesAlertState) IsExact() bool {
	if e != nil {
		switch *e {
		case "ok", "info", "warning", "in_alarm":
			return true
		}
	}
	return false
}
