// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesAddonAssociationEntityType string

const (
	TypesAddonAssociationEntityTypeSubscription TypesAddonAssociationEntityType = "subscription"
	TypesAddonAssociationEntityTypePlan         TypesAddonAssociationEntityType = "plan"
	TypesAddonAssociationEntityTypeAddon        TypesAddonAssociationEntityType = "addon"
)

func (e TypesAddonAssociationEntityType) ToPointer() *TypesAddonAssociationEntityType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesAddonAssociationEntityType) IsExact() bool {
	if e != nil {
		switch *e {
		case "subscription", "plan", "addon":
			return true
		}
	}
	return false
}
