// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/flexprice/go-sdk/internal/utils"
)

type TypesWalletFilterOrder string

const (
	TypesWalletFilterOrderAsc  TypesWalletFilterOrder = "asc"
	TypesWalletFilterOrderDesc TypesWalletFilterOrder = "desc"
)

func (e TypesWalletFilterOrder) ToPointer() *TypesWalletFilterOrder {
	return &e
}
func (e *TypesWalletFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = TypesWalletFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesWalletFilterOrder: %v", v)
	}
}

type TypesWalletFilter struct {
	AlertEnabled *bool                   `json:"alert_enabled,omitzero"`
	Expand       *string                 `json:"expand,omitzero"`
	Limit        *int64                  `json:"limit,omitzero"`
	Offset       *int64                  `json:"offset,omitzero"`
	Order        *TypesWalletFilterOrder `json:"order,omitzero"`
	Sort         *string                 `json:"sort,omitzero"`
	Status       *TypesWalletStatus      `json:"status,omitzero"`
	WalletIds    []string                `json:"wallet_ids,omitzero"`
}

func (t TypesWalletFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TypesWalletFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TypesWalletFilter) GetAlertEnabled() *bool {
	if t == nil {
		return nil
	}
	return t.AlertEnabled
}

func (t *TypesWalletFilter) GetExpand() *string {
	if t == nil {
		return nil
	}
	return t.Expand
}

func (t *TypesWalletFilter) GetLimit() *int64 {
	if t == nil {
		return nil
	}
	return t.Limit
}

func (t *TypesWalletFilter) GetOffset() *int64 {
	if t == nil {
		return nil
	}
	return t.Offset
}

func (t *TypesWalletFilter) GetOrder() *TypesWalletFilterOrder {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *TypesWalletFilter) GetSort() *string {
	if t == nil {
		return nil
	}
	return t.Sort
}

func (t *TypesWalletFilter) GetStatus() *TypesWalletStatus {
	if t == nil {
		return nil
	}
	return t.Status
}

func (t *TypesWalletFilter) GetWalletIds() []string {
	if t == nil {
		return nil
	}
	return t.WalletIds
}
