// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesPaymentMethodType string

const (
	TypesPaymentMethodTypeCard        TypesPaymentMethodType = "CARD"
	TypesPaymentMethodTypeAch         TypesPaymentMethodType = "ACH"
	TypesPaymentMethodTypeOffline     TypesPaymentMethodType = "OFFLINE"
	TypesPaymentMethodTypeCredits     TypesPaymentMethodType = "CREDITS"
	TypesPaymentMethodTypePaymentLink TypesPaymentMethodType = "PAYMENT_LINK"
)

func (e TypesPaymentMethodType) ToPointer() *TypesPaymentMethodType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesPaymentMethodType) IsExact() bool {
	if e != nil {
		switch *e {
		case "CARD", "ACH", "OFFLINE", "CREDITS", "PAYMENT_LINK":
			return true
		}
	}
	return false
}
