// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesPauseMode string

const (
	TypesPauseModeImmediate TypesPauseMode = "immediate"
	TypesPauseModeScheduled TypesPauseMode = "scheduled"
	TypesPauseModePeriodEnd TypesPauseMode = "period_end"
)

func (e TypesPauseMode) ToPointer() *TypesPauseMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesPauseMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "immediate", "scheduled", "period_end":
			return true
		}
	}
	return false
}
