// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 312f23882cfb

package components

type TypesTaskType string

const (
	TypesTaskTypeImport TypesTaskType = "IMPORT"
	TypesTaskTypeExport TypesTaskType = "EXPORT"
)

func (e TypesTaskType) ToPointer() *TypesTaskType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesTaskType) IsExact() bool {
	if e != nil {
		switch *e {
		case "IMPORT", "EXPORT":
			return true
		}
	}
	return false
}
