// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TypesResumeMode string

const (
	TypesResumeModeImmediate TypesResumeMode = "immediate"
	TypesResumeModeScheduled TypesResumeMode = "scheduled"
	TypesResumeModeAuto      TypesResumeMode = "auto"
)

func (e TypesResumeMode) ToPointer() *TypesResumeMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TypesResumeMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "immediate", "scheduled", "auto":
			return true
		}
	}
	return false
}
