// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TypesAlertThresholdType string

const (
	TypesAlertThresholdTypeAmount TypesAlertThresholdType = "amount"
)

func (e TypesAlertThresholdType) ToPointer() *TypesAlertThresholdType {
	return &e
}
func (e *TypesAlertThresholdType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "amount":
		*e = TypesAlertThresholdType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesAlertThresholdType: %v", v)
	}
}
