// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/flexprice/go-sdk/internal/utils"
)

type TypesConnectionFilterOrder string

const (
	TypesConnectionFilterOrderAsc  TypesConnectionFilterOrder = "asc"
	TypesConnectionFilterOrderDesc TypesConnectionFilterOrder = "desc"
)

func (e TypesConnectionFilterOrder) ToPointer() *TypesConnectionFilterOrder {
	return &e
}
func (e *TypesConnectionFilterOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = TypesConnectionFilterOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesConnectionFilterOrder: %v", v)
	}
}

type TypesConnectionFilter struct {
	ConnectionIds []string                    `json:"connection_ids,omitzero"`
	EndTime       *string                     `json:"end_time,omitzero"`
	Expand        *string                     `json:"expand,omitzero"`
	Filters       []TypesFilterCondition      `json:"filters,omitzero"`
	Limit         *int64                      `json:"limit,omitzero"`
	Offset        *int64                      `json:"offset,omitzero"`
	Order         *TypesConnectionFilterOrder `json:"order,omitzero"`
	ProviderType  *TypesSecretProvider        `json:"provider_type,omitzero"`
	Sort          []TypesSortCondition        `json:"sort,omitzero"`
	StartTime     *string                     `json:"start_time,omitzero"`
	Status        *TypesStatus                `json:"status,omitzero"`
}

func (t TypesConnectionFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TypesConnectionFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TypesConnectionFilter) GetConnectionIds() []string {
	if t == nil {
		return nil
	}
	return t.ConnectionIds
}

func (t *TypesConnectionFilter) GetEndTime() *string {
	if t == nil {
		return nil
	}
	return t.EndTime
}

func (t *TypesConnectionFilter) GetExpand() *string {
	if t == nil {
		return nil
	}
	return t.Expand
}

func (t *TypesConnectionFilter) GetFilters() []TypesFilterCondition {
	if t == nil {
		return nil
	}
	return t.Filters
}

func (t *TypesConnectionFilter) GetLimit() *int64 {
	if t == nil {
		return nil
	}
	return t.Limit
}

func (t *TypesConnectionFilter) GetOffset() *int64 {
	if t == nil {
		return nil
	}
	return t.Offset
}

func (t *TypesConnectionFilter) GetOrder() *TypesConnectionFilterOrder {
	if t == nil {
		return nil
	}
	return t.Order
}

func (t *TypesConnectionFilter) GetProviderType() *TypesSecretProvider {
	if t == nil {
		return nil
	}
	return t.ProviderType
}

func (t *TypesConnectionFilter) GetSort() []TypesSortCondition {
	if t == nil {
		return nil
	}
	return t.Sort
}

func (t *TypesConnectionFilter) GetStartTime() *string {
	if t == nil {
		return nil
	}
	return t.StartTime
}

func (t *TypesConnectionFilter) GetStatus() *TypesStatus {
	if t == nil {
		return nil
	}
	return t.Status
}
