// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type TypesPaymentBehavior string

const (
	TypesPaymentBehaviorAllowIncomplete   TypesPaymentBehavior = "allow_incomplete"
	TypesPaymentBehaviorDefaultIncomplete TypesPaymentBehavior = "default_incomplete"
	TypesPaymentBehaviorErrorIfIncomplete TypesPaymentBehavior = "error_if_incomplete"
	TypesPaymentBehaviorDefaultActive     TypesPaymentBehavior = "default_active"
)

func (e TypesPaymentBehavior) ToPointer() *TypesPaymentBehavior {
	return &e
}
func (e *TypesPaymentBehavior) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow_incomplete":
		fallthrough
	case "default_incomplete":
		fallthrough
	case "error_if_incomplete":
		fallthrough
	case "default_active":
		*e = TypesPaymentBehavior(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypesPaymentBehavior: %v", v)
	}
}
