/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 96984d735540
 */

import * as z from "zod/v4-mini";
import { FlexpriceCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { FlexpriceError } from "../models/errors/flexpriceerror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * List entity integration mappings
 *
 * @remarks
 * Retrieve a list of entity integration mappings with optional filtering
 */
export function entityIntegrationMappingsList(
  client: FlexpriceCore,
  entityId?: string | undefined,
  entityType?: string | undefined,
  providerType?: string | undefined,
  providerEntityId?: string | undefined,
  limit?: number | undefined,
  offset?: number | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    models.DtoListEntityIntegrationMappingsResponse,
    | errors.ErrorsErrorResponse
    | FlexpriceError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    entityId,
    entityType,
    providerType,
    providerEntityId,
    limit,
    offset,
    options,
  ));
}

async function $do(
  client: FlexpriceCore,
  entityId?: string | undefined,
  entityType?: string | undefined,
  providerType?: string | undefined,
  providerEntityId?: string | undefined,
  limit?: number | undefined,
  offset?: number | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      models.DtoListEntityIntegrationMappingsResponse,
      | errors.ErrorsErrorResponse
      | FlexpriceError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: operations.GetEntityIntegrationMappingsRequest | undefined = {
    entityId: entityId,
    entityType: entityType,
    providerType: providerType,
    providerEntityId: providerEntityId,
    limit: limit,
    offset: offset,
  };

  const parsed = safeParse(
    input,
    (value) =>
      z.parse(
        z.optional(
          operations.GetEntityIntegrationMappingsRequest$outboundSchema,
        ),
        value,
      ),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const path = pathToFunc("/entity-integration-mappings")();

  const query = encodeFormQuery({
    "entity_id": payload?.entity_id,
    "entity_type": payload?.entity_type,
    "limit": payload?.limit,
    "offset": payload?.offset,
    "provider_entity_id": payload?.provider_entity_id,
    "provider_type": payload?.provider_type,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKeyAuth);
  const securityInput = secConfig == null ? {} : { apiKeyAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "get_/entity-integration-mappings",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKeyAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "401", "4XX", "500", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    models.DtoListEntityIntegrationMappingsResponse,
    | errors.ErrorsErrorResponse
    | FlexpriceError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, models.DtoListEntityIntegrationMappingsResponse$inboundSchema),
    M.jsonErr([400, 401], errors.ErrorsErrorResponse$inboundSchema),
    M.jsonErr(500, errors.ErrorsErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
