/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 2483219bba9f
 */

import { entityIntegrationMappingsCreate } from "../funcs/entityIntegrationMappingsCreate.js";
import { entityIntegrationMappingsDelete } from "../funcs/entityIntegrationMappingsDelete.js";
import { entityIntegrationMappingsGetById } from "../funcs/entityIntegrationMappingsGetById.js";
import { entityIntegrationMappingsList } from "../funcs/entityIntegrationMappingsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EntityIntegrationMappings extends ClientSDK {
  /**
   * List entity integration mappings
   *
   * @remarks
   * Retrieve a list of entity integration mappings with optional filtering
   */
  async list(
    entityId?: string | undefined,
    entityType?: string | undefined,
    providerType?: string | undefined,
    providerEntityId?: string | undefined,
    limit?: number | undefined,
    offset?: number | undefined,
    options?: RequestOptions,
  ): Promise<models.DtoListEntityIntegrationMappingsResponse> {
    return unwrapAsync(entityIntegrationMappingsList(
      this,
      entityId,
      entityType,
      providerType,
      providerEntityId,
      limit,
      offset,
      options,
    ));
  }

  /**
   * Create entity integration mapping
   *
   * @remarks
   * Create a new entity integration mapping
   */
  async create(
    request: models.DtoCreateEntityIntegrationMappingRequest,
    options?: RequestOptions,
  ): Promise<models.DtoEntityIntegrationMappingResponse> {
    return unwrapAsync(entityIntegrationMappingsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get entity integration mapping
   *
   * @remarks
   * Retrieve a specific entity integration mapping by ID
   */
  async getById(
    id: string,
    options?: RequestOptions,
  ): Promise<models.DtoEntityIntegrationMappingResponse> {
    return unwrapAsync(entityIntegrationMappingsGetById(
      this,
      id,
      options,
    ));
  }

  /**
   * Delete entity integration mapping
   *
   * @remarks
   * Delete an entity integration mapping
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(entityIntegrationMappingsDelete(
      this,
      id,
      options,
    ));
  }
}
