/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: be304b988e92
 */

import { featuresCreate } from "../funcs/featuresCreate.js";
import { featuresDelete } from "../funcs/featuresDelete.js";
import { featuresGetById } from "../funcs/featuresGetById.js";
import { featuresList } from "../funcs/featuresList.js";
import { featuresSearch } from "../funcs/featuresSearch.js";
import { featuresUpdate } from "../funcs/featuresUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Features extends ClientSDK {
  /**
   * List features
   *
   * @remarks
   * List features with optional filtering
   */
  async list(
    endTime?: string | undefined,
    expand?: string | undefined,
    featureIds?: Array<string> | undefined,
    limit?: number | undefined,
    lookupKey?: string | undefined,
    lookupKeys?: Array<string> | undefined,
    meterIds?: Array<string> | undefined,
    nameContains?: string | undefined,
    offset?: number | undefined,
    order?: operations.GetFeaturesQueryParamOrder | undefined,
    startTime?: string | undefined,
    status?: operations.GetFeaturesQueryParamStatus | undefined,
    options?: RequestOptions,
  ): Promise<models.DtoListFeaturesResponse> {
    return unwrapAsync(featuresList(
      this,
      endTime,
      expand,
      featureIds,
      limit,
      lookupKey,
      lookupKeys,
      meterIds,
      nameContains,
      offset,
      order,
      startTime,
      status,
      options,
    ));
  }

  /**
   * Create a new feature
   *
   * @remarks
   * Create a new feature
   */
  async create(
    request: models.DtoCreateFeatureRequest,
    options?: RequestOptions,
  ): Promise<models.DtoFeatureResponse> {
    return unwrapAsync(featuresCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List features by filter
   *
   * @remarks
   * List features by filter
   */
  async search(
    request: models.TypesFeatureFilter,
    options?: RequestOptions,
  ): Promise<models.DtoListFeaturesResponse> {
    return unwrapAsync(featuresSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a feature by ID
   *
   * @remarks
   * Get a feature by ID
   */
  async getById(
    id: string,
    options?: RequestOptions,
  ): Promise<models.DtoFeatureResponse> {
    return unwrapAsync(featuresGetById(
      this,
      id,
      options,
    ));
  }

  /**
   * Update a feature
   *
   * @remarks
   * Update a feature by ID
   */
  async update(
    id: string,
    body: models.DtoUpdateFeatureRequest,
    options?: RequestOptions,
  ): Promise<models.DtoFeatureResponse> {
    return unwrapAsync(featuresUpdate(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * Delete a feature
   *
   * @remarks
   * Delete a feature by ID
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<{ [k: string]: models.GinH }> {
    return unwrapAsync(featuresDelete(
      this,
      id,
      options,
    ));
  }
}
