/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersGetUsersMe } from "../funcs/usersGetUsersMe.js";
import { usersPostUsers } from "../funcs/usersPostUsers.js";
import { usersPostUsersSearch } from "../funcs/usersPostUsersSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Users extends ClientSDK {
  /**
   * Create service account
   *
   * @remarks
   * Create a new service account with required roles. Only service accounts can be created via this endpoint.
   */
  async postUsers(
    request: components.DtoCreateUserRequest,
    options?: RequestOptions,
  ): Promise<components.DtoUserResponse> {
    return unwrapAsync(usersPostUsers(
      this,
      request,
      options,
    ));
  }

  /**
   * Get user info
   *
   * @remarks
   * Get the current user's information
   */
  async getUsersMe(
    options?: RequestOptions,
  ): Promise<components.DtoUserResponse> {
    return unwrapAsync(usersGetUsersMe(
      this,
      options,
    ));
  }

  /**
   * List users with filters
   *
   * @remarks
   * Search and filter users by type (user/service_account), roles, etc.
   */
  async postUsersSearch(
    request: components.TypesUserFilter,
    options?: RequestOptions,
  ): Promise<components.DtoListUsersResponse> {
    return unwrapAsync(usersPostUsersSearch(
      this,
      request,
      options,
    ));
  }
}
