/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { walletsGetCustomersIdWallets } from "../funcs/walletsGetCustomersIdWallets.js";
import { walletsGetCustomersWallets } from "../funcs/walletsGetCustomersWallets.js";
import { walletsGetWallets } from "../funcs/walletsGetWallets.js";
import { walletsGetWalletsId } from "../funcs/walletsGetWalletsId.js";
import { walletsGetWalletsIdBalanceRealTime } from "../funcs/walletsGetWalletsIdBalanceRealTime.js";
import { walletsGetWalletsIdTransactions } from "../funcs/walletsGetWalletsIdTransactions.js";
import { walletsPostWallets } from "../funcs/walletsPostWallets.js";
import { walletsPostWalletsIdTerminate } from "../funcs/walletsPostWalletsIdTerminate.js";
import { walletsPostWalletsIdTopUp } from "../funcs/walletsPostWalletsIdTopUp.js";
import { walletsPostWalletsSearch } from "../funcs/walletsPostWalletsSearch.js";
import { walletsPostWalletsTransactionsSearch } from "../funcs/walletsPostWalletsTransactionsSearch.js";
import { walletsPutWalletsId } from "../funcs/walletsPutWalletsId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Wallets extends ClientSDK {
  /**
   * Get Customer Wallets
   *
   * @remarks
   * Get all wallets for a customer by lookup key or id
   */
  async getCustomersWallets(
    id?: string | undefined,
    includeRealTimeBalance?: boolean | undefined,
    lookupKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<Array<components.DtoWalletResponse>> {
    return unwrapAsync(walletsGetCustomersWallets(
      this,
      id,
      includeRealTimeBalance,
      lookupKey,
      options,
    ));
  }

  /**
   * Get wallets by customer ID
   *
   * @remarks
   * Get all wallets for a customer
   */
  async getCustomersIdWallets(
    id: string,
    options?: RequestOptions,
  ): Promise<Array<components.DtoWalletResponse>> {
    return unwrapAsync(walletsGetCustomersIdWallets(
      this,
      id,
      options,
    ));
  }

  /**
   * List wallets
   *
   * @remarks
   * List wallets with optional filtering
   */
  async getWallets(
    request: operations.GetWalletsRequest,
    options?: RequestOptions,
  ): Promise<components.TypesListResponseDtoWalletResponse> {
    return unwrapAsync(walletsGetWallets(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new wallet
   *
   * @remarks
   * Create a new wallet for a customer
   */
  async postWallets(
    request: components.DtoCreateWalletRequest,
    options?: RequestOptions,
  ): Promise<components.DtoWalletResponse> {
    return unwrapAsync(walletsPostWallets(
      this,
      request,
      options,
    ));
  }

  /**
   * List wallets by filter
   *
   * @remarks
   * List wallets by filter
   */
  async postWalletsSearch(
    request?: components.TypesWalletFilter | undefined,
    options?: RequestOptions,
  ): Promise<components.TypesListResponseDtoWalletResponse> {
    return unwrapAsync(walletsPostWalletsSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * List wallet transactions by filter
   *
   * @remarks
   * List wallet transactions by filter
   */
  async postWalletsTransactionsSearch(
    expand?: string | undefined,
    body?: components.TypesWalletTransactionFilter | undefined,
    options?: RequestOptions,
  ): Promise<components.DtoListWalletTransactionsResponse> {
    return unwrapAsync(walletsPostWalletsTransactionsSearch(
      this,
      expand,
      body,
      options,
    ));
  }

  /**
   * Get wallet by ID
   *
   * @remarks
   * Get a wallet by its ID
   */
  async getWalletsId(
    id: string,
    options?: RequestOptions,
  ): Promise<components.DtoWalletResponse> {
    return unwrapAsync(walletsGetWalletsId(
      this,
      id,
      options,
    ));
  }

  /**
   * Update a wallet
   *
   * @remarks
   * Update a wallet's details including auto top-up configuration
   */
  async putWalletsId(
    id: string,
    body: components.DtoUpdateWalletRequest,
    options?: RequestOptions,
  ): Promise<components.DtoWalletResponse> {
    return unwrapAsync(walletsPutWalletsId(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * Get wallet balance
   *
   * @remarks
   * Get real-time balance of a wallet
   */
  async getWalletsIdBalanceRealTime(
    id: string,
    options?: RequestOptions,
  ): Promise<components.DtoWalletBalanceResponse> {
    return unwrapAsync(walletsGetWalletsIdBalanceRealTime(
      this,
      id,
      options,
    ));
  }

  /**
   * Terminate a wallet
   *
   * @remarks
   * Terminates a wallet by closing it and debiting remaining balance
   */
  async postWalletsIdTerminate(
    id: string,
    options?: RequestOptions,
  ): Promise<components.DtoWalletResponse> {
    return unwrapAsync(walletsPostWalletsIdTerminate(
      this,
      id,
      options,
    ));
  }

  /**
   * Top up wallet
   *
   * @remarks
   * Add credits to a wallet
   */
  async postWalletsIdTopUp(
    id: string,
    body: components.DtoTopUpWalletRequest,
    options?: RequestOptions,
  ): Promise<components.DtoTopUpWalletResponse> {
    return unwrapAsync(walletsPostWalletsIdTopUp(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * Get wallet transactions
   *
   * @remarks
   * Get transactions for a wallet with pagination
   */
  async getWalletsIdTransactions(
    request: operations.GetWalletsIdTransactionsRequest,
    options?: RequestOptions,
  ): Promise<components.DtoListWalletTransactionsResponse> {
    return unwrapAsync(walletsGetWalletsIdTransactions(
      this,
      request,
      options,
    ));
  }
}
