/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e1f49fcc065d
 */

import * as z from "zod/v4-mini";

export type DeleteGroupsIdRequest = {
  /**
   * Group ID
   */
  id: string;
};

/** @internal */
export type DeleteGroupsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteGroupsIdRequest$outboundSchema: z.ZodMiniType<
  DeleteGroupsIdRequest$Outbound,
  DeleteGroupsIdRequest
> = z.object({
  id: z.string(),
});

export function deleteGroupsIdRequestToJSON(
  deleteGroupsIdRequest: DeleteGroupsIdRequest,
): string {
  return JSON.stringify(
    DeleteGroupsIdRequest$outboundSchema.parse(deleteGroupsIdRequest),
  );
}
