/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 39f1c51e001b
 */

import * as z from "zod/v4-mini";

export type GetCostsIdRequest = {
  /**
   * Costsheet ID
   */
  id: string;
  /**
   * Comma-separated list of fields to expand (e.g., 'prices')
   */
  expand?: string | undefined;
};

/** @internal */
export type GetCostsIdRequest$Outbound = {
  id: string;
  expand?: string | undefined;
};

/** @internal */
export const GetCostsIdRequest$outboundSchema: z.ZodMiniType<
  GetCostsIdRequest$Outbound,
  GetCostsIdRequest
> = z.object({
  id: z.string(),
  expand: z.optional(z.string()),
});

export function getCostsIdRequestToJSON(
  getCostsIdRequest: GetCostsIdRequest,
): string {
  return JSON.stringify(
    GetCostsIdRequest$outboundSchema.parse(getCostsIdRequest),
  );
}
