/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetCouponsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetCouponsOrder = ClosedEnum<typeof GetCouponsOrder>;

export const GetCouponsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetCouponsStatus = ClosedEnum<typeof GetCouponsStatus>;

export type GetCouponsRequest = {
  couponIds?: Array<string> | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetCouponsOrder | undefined;
  status?: GetCouponsStatus | undefined;
};

/** @internal */
export const GetCouponsOrder$outboundSchema: z.ZodMiniEnum<
  typeof GetCouponsOrder
> = z.enum(GetCouponsOrder);

/** @internal */
export const GetCouponsStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetCouponsStatus
> = z.enum(GetCouponsStatus);

/** @internal */
export type GetCouponsRequest$Outbound = {
  coupon_ids?: Array<string> | undefined;
  expand?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const GetCouponsRequest$outboundSchema: z.ZodMiniType<
  GetCouponsRequest$Outbound,
  GetCouponsRequest
> = z.pipe(
  z.object({
    couponIds: z.optional(z.array(z.string())),
    expand: z.optional(z.string()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(GetCouponsOrder$outboundSchema),
    status: z.optional(GetCouponsStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      couponIds: "coupon_ids",
    });
  }),
);

export function getCouponsRequestToJSON(
  getCouponsRequest: GetCouponsRequest,
): string {
  return JSON.stringify(
    GetCouponsRequest$outboundSchema.parse(getCouponsRequest),
  );
}
