/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c5943673a26c
 */

import * as z from "zod/v4-mini";

export type GetCustomersIdGrantsUpcomingRequest = {
  /**
   * Customer ID
   */
  id: string;
};

/** @internal */
export type GetCustomersIdGrantsUpcomingRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomersIdGrantsUpcomingRequest$outboundSchema: z.ZodMiniType<
  GetCustomersIdGrantsUpcomingRequest$Outbound,
  GetCustomersIdGrantsUpcomingRequest
> = z.object({
  id: z.string(),
});

export function getCustomersIdGrantsUpcomingRequestToJSON(
  getCustomersIdGrantsUpcomingRequest: GetCustomersIdGrantsUpcomingRequest,
): string {
  return JSON.stringify(
    GetCustomersIdGrantsUpcomingRequest$outboundSchema.parse(
      getCustomersIdGrantsUpcomingRequest,
    ),
  );
}
