/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetEntityIntegrationMappingsRequest = {
  /**
   * Filter by FlexPrice entity ID
   */
  entityId?: string | undefined;
  /**
   * Filter by entity type
   */
  entityType?: string | undefined;
  /**
   * Filter by provider type
   */
  providerType?: string | undefined;
  /**
   * Filter by provider entity ID
   */
  providerEntityId?: string | undefined;
  /**
   * Number of results to return (default: 20, max: 100)
   */
  limit?: number | undefined;
  /**
   * Pagination offset (default: 0)
   */
  offset?: number | undefined;
};

/** @internal */
export type GetEntityIntegrationMappingsRequest$Outbound = {
  entity_id?: string | undefined;
  entity_type?: string | undefined;
  provider_type?: string | undefined;
  provider_entity_id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const GetEntityIntegrationMappingsRequest$outboundSchema: z.ZodMiniType<
  GetEntityIntegrationMappingsRequest$Outbound,
  GetEntityIntegrationMappingsRequest
> = z.pipe(
  z.object({
    entityId: z.optional(z.string()),
    entityType: z.optional(z.string()),
    providerType: z.optional(z.string()),
    providerEntityId: z.optional(z.string()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      entityId: "entity_id",
      entityType: "entity_type",
      providerType: "provider_type",
      providerEntityId: "provider_entity_id",
    });
  }),
);

export function getEntityIntegrationMappingsRequestToJSON(
  getEntityIntegrationMappingsRequest: GetEntityIntegrationMappingsRequest,
): string {
  return JSON.stringify(
    GetEntityIntegrationMappingsRequest$outboundSchema.parse(
      getEntityIntegrationMappingsRequest,
    ),
  );
}
