/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bbace6786b8d
 */

import * as z from "zod/v4-mini";

export type GetEntitlementsIdRequest = {
  /**
   * Entitlement ID
   */
  id: string;
};

/** @internal */
export type GetEntitlementsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEntitlementsIdRequest$outboundSchema: z.ZodMiniType<
  GetEntitlementsIdRequest$Outbound,
  GetEntitlementsIdRequest
> = z.object({
  id: z.string(),
});

export function getEntitlementsIdRequestToJSON(
  getEntitlementsIdRequest: GetEntitlementsIdRequest,
): string {
  return JSON.stringify(
    GetEntitlementsIdRequest$outboundSchema.parse(getEntitlementsIdRequest),
  );
}
