/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 60569fe1ec22
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetEventsMonitoringRequest = {
  /**
   * Window size for time series data (e.g., 'HOUR', 'DAY') - optional
   */
  windowSize?: string | undefined;
};

/** @internal */
export type GetEventsMonitoringRequest$Outbound = {
  window_size?: string | undefined;
};

/** @internal */
export const GetEventsMonitoringRequest$outboundSchema: z.ZodMiniType<
  GetEventsMonitoringRequest$Outbound,
  GetEventsMonitoringRequest
> = z.pipe(
  z.object({
    windowSize: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      windowSize: "window_size",
    });
  }),
);

export function getEventsMonitoringRequestToJSON(
  getEventsMonitoringRequest: GetEventsMonitoringRequest,
): string {
  return JSON.stringify(
    GetEventsMonitoringRequest$outboundSchema.parse(getEventsMonitoringRequest),
  );
}
