/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8acc75dc8cfd
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const InvoiceStatus = {
  Draft: "DRAFT",
  Finalized: "FINALIZED",
  Voided: "VOIDED",
} as const;
export type InvoiceStatus = ClosedEnum<typeof InvoiceStatus>;

/**
 * invoice_type filters by the nature of the invoice (SUBSCRIPTION, ONE_OFF, or CREDIT)
 *
 * @remarks
 * Use this to separate recurring charges from one-time fees or credit adjustments
 */
export const InvoiceType = {
  Subscription: "SUBSCRIPTION",
  OneOff: "ONE_OFF",
  Credit: "CREDIT",
} as const;
/**
 * invoice_type filters by the nature of the invoice (SUBSCRIPTION, ONE_OFF, or CREDIT)
 *
 * @remarks
 * Use this to separate recurring charges from one-time fees or credit adjustments
 */
export type InvoiceType = ClosedEnum<typeof InvoiceType>;

export const GetInvoicesQueryParamOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetInvoicesQueryParamOrder = ClosedEnum<
  typeof GetInvoicesQueryParamOrder
>;

export const PaymentStatus = {
  Initiated: "INITIATED",
  Pending: "PENDING",
  Processing: "PROCESSING",
  Succeeded: "SUCCEEDED",
  Overpaid: "OVERPAID",
  Failed: "FAILED",
  Refunded: "REFUNDED",
  PartiallyRefunded: "PARTIALLY_REFUNDED",
} as const;
export type PaymentStatus = ClosedEnum<typeof PaymentStatus>;

export const GetInvoicesQueryParamStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetInvoicesQueryParamStatus = ClosedEnum<
  typeof GetInvoicesQueryParamStatus
>;

export type GetInvoicesRequest = {
  /**
   * amount_due_gt filters invoices with a total amount due greater than the specified value
   *
   * @remarks
   * Useful for finding invoices above a certain threshold or identifying high-value invoices
   */
  amountDueGt?: number | undefined;
  /**
   * amount_remaining_gt filters invoices with an outstanding balance greater than the specified value
   *
   * @remarks
   * Useful for finding invoices that still have significant unpaid amounts
   */
  amountRemainingGt?: number | undefined;
  /**
   * customer_id filters invoices for a specific customer using FlexPrice's internal customer ID
   *
   * @remarks
   * This is the ID returned by FlexPrice when creating or retrieving customers
   */
  customerId?: string | undefined;
  endTime?: string | undefined;
  expand?: string | undefined;
  /**
   * external_customer_id filters invoices for a customer using your system's customer identifier
   *
   * @remarks
   * This is the ID you provided when creating the customer in FlexPrice
   */
  externalCustomerId?: string | undefined;
  /**
   * invoice_ids restricts results to invoices with the specified IDs
   *
   * @remarks
   * Use this to retrieve specific invoices when you know their exact identifiers
   */
  invoiceIds?: Array<string> | undefined;
  /**
   * invoice_status filters by the current state of invoices in their lifecycle
   *
   * @remarks
   * Multiple statuses can be specified to include invoices in any of the listed states
   */
  invoiceStatus?: Array<InvoiceStatus> | undefined;
  /**
   * invoice_type filters by the nature of the invoice (SUBSCRIPTION, ONE_OFF, or CREDIT)
   *
   * @remarks
   * Use this to separate recurring charges from one-time fees or credit adjustments
   */
  invoiceType?: InvoiceType | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetInvoicesQueryParamOrder | undefined;
  /**
   * payment_status filters by the payment state of invoices
   *
   * @remarks
   * Multiple statuses can be specified to include invoices with any of the listed payment states
   */
  paymentStatus?: Array<PaymentStatus> | undefined;
  /**
   * SkipLineItems if true, will not include line items in the response
   */
  skipLineItems?: boolean | undefined;
  startTime?: string | undefined;
  status?: GetInvoicesQueryParamStatus | undefined;
  /**
   * subscription_id filters invoices generated for a specific subscription
   *
   * @remarks
   * Only returns invoices that were created as part of the specified subscription's billing
   */
  subscriptionId?: string | undefined;
};

/** @internal */
export const InvoiceStatus$outboundSchema: z.ZodMiniEnum<typeof InvoiceStatus> =
  z.enum(InvoiceStatus);

/** @internal */
export const InvoiceType$outboundSchema: z.ZodMiniEnum<typeof InvoiceType> = z
  .enum(InvoiceType);

/** @internal */
export const GetInvoicesQueryParamOrder$outboundSchema: z.ZodMiniEnum<
  typeof GetInvoicesQueryParamOrder
> = z.enum(GetInvoicesQueryParamOrder);

/** @internal */
export const PaymentStatus$outboundSchema: z.ZodMiniEnum<typeof PaymentStatus> =
  z.enum(PaymentStatus);

/** @internal */
export const GetInvoicesQueryParamStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetInvoicesQueryParamStatus
> = z.enum(GetInvoicesQueryParamStatus);

/** @internal */
export type GetInvoicesRequest$Outbound = {
  amount_due_gt?: number | undefined;
  amount_remaining_gt?: number | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  invoice_ids?: Array<string> | undefined;
  invoice_status?: Array<string> | undefined;
  invoice_type?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  payment_status?: Array<string> | undefined;
  skip_line_items?: boolean | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
  subscription_id?: string | undefined;
};

/** @internal */
export const GetInvoicesRequest$outboundSchema: z.ZodMiniType<
  GetInvoicesRequest$Outbound,
  GetInvoicesRequest
> = z.pipe(
  z.object({
    amountDueGt: z.optional(z.number()),
    amountRemainingGt: z.optional(z.number()),
    customerId: z.optional(z.string()),
    endTime: z.optional(z.string()),
    expand: z.optional(z.string()),
    externalCustomerId: z.optional(z.string()),
    invoiceIds: z.optional(z.array(z.string())),
    invoiceStatus: z.optional(z.array(InvoiceStatus$outboundSchema)),
    invoiceType: z.optional(InvoiceType$outboundSchema),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(GetInvoicesQueryParamOrder$outboundSchema),
    paymentStatus: z.optional(z.array(PaymentStatus$outboundSchema)),
    skipLineItems: z.optional(z.boolean()),
    startTime: z.optional(z.string()),
    status: z.optional(GetInvoicesQueryParamStatus$outboundSchema),
    subscriptionId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      amountDueGt: "amount_due_gt",
      amountRemainingGt: "amount_remaining_gt",
      customerId: "customer_id",
      endTime: "end_time",
      externalCustomerId: "external_customer_id",
      invoiceIds: "invoice_ids",
      invoiceStatus: "invoice_status",
      invoiceType: "invoice_type",
      paymentStatus: "payment_status",
      skipLineItems: "skip_line_items",
      startTime: "start_time",
      subscriptionId: "subscription_id",
    });
  }),
);

export function getInvoicesRequestToJSON(
  getInvoicesRequest: GetInvoicesRequest,
): string {
  return JSON.stringify(
    GetInvoicesRequest$outboundSchema.parse(getInvoicesRequest),
  );
}
