/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 12464fb76099
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetPaymentsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetPaymentsOrder = ClosedEnum<typeof GetPaymentsOrder>;

export const GetPaymentsStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetPaymentsStatus = ClosedEnum<typeof GetPaymentsStatus>;

export type GetPaymentsRequest = {
  currency?: string | undefined;
  destinationId?: string | undefined;
  destinationType?: string | undefined;
  endTime?: string | undefined;
  expand?: string | undefined;
  gatewayPaymentId?: string | undefined;
  /**
   * For filtering by gateway tracking ID
   */
  gatewayTrackingId?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetPaymentsOrder | undefined;
  paymentGateway?: string | undefined;
  paymentIds?: Array<string> | undefined;
  paymentMethodType?: string | undefined;
  paymentStatus?: string | undefined;
  sort?: string | undefined;
  startTime?: string | undefined;
  status?: GetPaymentsStatus | undefined;
};

/** @internal */
export const GetPaymentsOrder$outboundSchema: z.ZodMiniEnum<
  typeof GetPaymentsOrder
> = z.enum(GetPaymentsOrder);

/** @internal */
export const GetPaymentsStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetPaymentsStatus
> = z.enum(GetPaymentsStatus);

/** @internal */
export type GetPaymentsRequest$Outbound = {
  currency?: string | undefined;
  destination_id?: string | undefined;
  destination_type?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  gateway_payment_id?: string | undefined;
  gateway_tracking_id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  payment_gateway?: string | undefined;
  payment_ids?: Array<string> | undefined;
  payment_method_type?: string | undefined;
  payment_status?: string | undefined;
  sort?: string | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const GetPaymentsRequest$outboundSchema: z.ZodMiniType<
  GetPaymentsRequest$Outbound,
  GetPaymentsRequest
> = z.pipe(
  z.object({
    currency: z.optional(z.string()),
    destinationId: z.optional(z.string()),
    destinationType: z.optional(z.string()),
    endTime: z.optional(z.string()),
    expand: z.optional(z.string()),
    gatewayPaymentId: z.optional(z.string()),
    gatewayTrackingId: z.optional(z.string()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(GetPaymentsOrder$outboundSchema),
    paymentGateway: z.optional(z.string()),
    paymentIds: z.optional(z.array(z.string())),
    paymentMethodType: z.optional(z.string()),
    paymentStatus: z.optional(z.string()),
    sort: z.optional(z.string()),
    startTime: z.optional(z.string()),
    status: z.optional(GetPaymentsStatus$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      destinationId: "destination_id",
      destinationType: "destination_type",
      endTime: "end_time",
      gatewayPaymentId: "gateway_payment_id",
      gatewayTrackingId: "gateway_tracking_id",
      paymentGateway: "payment_gateway",
      paymentIds: "payment_ids",
      paymentMethodType: "payment_method_type",
      paymentStatus: "payment_status",
      startTime: "start_time",
    });
  }),
);

export function getPaymentsRequestToJSON(
  getPaymentsRequest: GetPaymentsRequest,
): string {
  return JSON.stringify(
    GetPaymentsRequest$outboundSchema.parse(getPaymentsRequest),
  );
}
