/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 48c608cf5634
 */

import * as z from "zod/v4-mini";

export type GetPlansIdRequest = {
  /**
   * Plan ID
   */
  id: string;
};

/** @internal */
export type GetPlansIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetPlansIdRequest$outboundSchema: z.ZodMiniType<
  GetPlansIdRequest$Outbound,
  GetPlansIdRequest
> = z.object({
  id: z.string(),
});

export function getPlansIdRequestToJSON(
  getPlansIdRequest: GetPlansIdRequest,
): string {
  return JSON.stringify(
    GetPlansIdRequest$outboundSchema.parse(getPlansIdRequest),
  );
}
