/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6ead93f79faa
 */

import * as z from "zod/v4-mini";

export type GetSubscriptionsIdPausesRequest = {
  /**
   * Subscription ID
   */
  id: string;
};

/** @internal */
export type GetSubscriptionsIdPausesRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSubscriptionsIdPausesRequest$outboundSchema: z.ZodMiniType<
  GetSubscriptionsIdPausesRequest$Outbound,
  GetSubscriptionsIdPausesRequest
> = z.object({
  id: z.string(),
});

export function getSubscriptionsIdPausesRequestToJSON(
  getSubscriptionsIdPausesRequest: GetSubscriptionsIdPausesRequest,
): string {
  return JSON.stringify(
    GetSubscriptionsIdPausesRequest$outboundSchema.parse(
      getSubscriptionsIdPausesRequest,
    ),
  );
}
