/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: fee51f173d83
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetTaxesAssociationsRequest = {
  /**
   * Entity Type
   */
  entityType?: string | undefined;
  /**
   * Entity ID
   */
  entityId?: string | undefined;
  /**
   * Tax Rate ID
   */
  taxRateId?: string | undefined;
};

/** @internal */
export type GetTaxesAssociationsRequest$Outbound = {
  entity_type?: string | undefined;
  entity_id?: string | undefined;
  tax_rate_id?: string | undefined;
};

/** @internal */
export const GetTaxesAssociationsRequest$outboundSchema: z.ZodMiniType<
  GetTaxesAssociationsRequest$Outbound,
  GetTaxesAssociationsRequest
> = z.pipe(
  z.object({
    entityType: z.optional(z.string()),
    entityId: z.optional(z.string()),
    taxRateId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      entityType: "entity_type",
      entityId: "entity_id",
      taxRateId: "tax_rate_id",
    });
  }),
);

export function getTaxesAssociationsRequestToJSON(
  getTaxesAssociationsRequest: GetTaxesAssociationsRequest,
): string {
  return JSON.stringify(
    GetTaxesAssociationsRequest$outboundSchema.parse(
      getTaxesAssociationsRequest,
    ),
  );
}
