/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b0339fcd79a6
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const GetWalletsIdTransactionsQueryParamOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type GetWalletsIdTransactionsQueryParamOrder = ClosedEnum<
  typeof GetWalletsIdTransactionsQueryParamOrder
>;

export const GetWalletsIdTransactionsQueryParamStatus = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type GetWalletsIdTransactionsQueryParamStatus = ClosedEnum<
  typeof GetWalletsIdTransactionsQueryParamStatus
>;

export const TransactionReason = {
  InvoicePayment: "INVOICE_PAYMENT",
  FreeCreditGrant: "FREE_CREDIT_GRANT",
  SubscriptionCreditGrant: "SUBSCRIPTION_CREDIT_GRANT",
  PurchasedCreditInvoiced: "PURCHASED_CREDIT_INVOICED",
  PurchasedCreditDirect: "PURCHASED_CREDIT_DIRECT",
  CreditNote: "CREDIT_NOTE",
  CreditExpired: "CREDIT_EXPIRED",
  WalletTermination: "WALLET_TERMINATION",
  ManualBalanceDebit: "MANUAL_BALANCE_DEBIT",
} as const;
export type TransactionReason = ClosedEnum<typeof TransactionReason>;

export const TransactionStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
} as const;
export type TransactionStatus = ClosedEnum<typeof TransactionStatus>;

export const Type = {
  Credit: "credit",
  Debit: "debit",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type GetWalletsIdTransactionsRequest = {
  /**
   * Wallet ID
   */
  idPathParameter: string;
  creditsAvailableGt?: number | undefined;
  endTime?: string | undefined;
  expand?: string | undefined;
  expiryDateAfter?: string | undefined;
  expiryDateBefore?: string | undefined;
  idQueryParameter?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: GetWalletsIdTransactionsQueryParamOrder | undefined;
  priority?: number | undefined;
  referenceId?: string | undefined;
  referenceType?: string | undefined;
  sort?: string | undefined;
  startTime?: string | undefined;
  status?: GetWalletsIdTransactionsQueryParamStatus | undefined;
  transactionReason?: TransactionReason | undefined;
  transactionStatus?: TransactionStatus | undefined;
  type?: Type | undefined;
};

/** @internal */
export const GetWalletsIdTransactionsQueryParamOrder$outboundSchema:
  z.ZodMiniEnum<typeof GetWalletsIdTransactionsQueryParamOrder> = z.enum(
    GetWalletsIdTransactionsQueryParamOrder,
  );

/** @internal */
export const GetWalletsIdTransactionsQueryParamStatus$outboundSchema:
  z.ZodMiniEnum<typeof GetWalletsIdTransactionsQueryParamStatus> = z.enum(
    GetWalletsIdTransactionsQueryParamStatus,
  );

/** @internal */
export const TransactionReason$outboundSchema: z.ZodMiniEnum<
  typeof TransactionReason
> = z.enum(TransactionReason);

/** @internal */
export const TransactionStatus$outboundSchema: z.ZodMiniEnum<
  typeof TransactionStatus
> = z.enum(TransactionStatus);

/** @internal */
export const Type$outboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type);

/** @internal */
export type GetWalletsIdTransactionsRequest$Outbound = {
  idPathParameter: string;
  credits_available_gt?: number | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  expiry_date_after?: string | undefined;
  expiry_date_before?: string | undefined;
  idQueryParameter?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  priority?: number | undefined;
  reference_id?: string | undefined;
  reference_type?: string | undefined;
  sort?: string | undefined;
  start_time?: string | undefined;
  status?: string | undefined;
  transaction_reason?: string | undefined;
  transaction_status?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const GetWalletsIdTransactionsRequest$outboundSchema: z.ZodMiniType<
  GetWalletsIdTransactionsRequest$Outbound,
  GetWalletsIdTransactionsRequest
> = z.pipe(
  z.object({
    idPathParameter: z.string(),
    creditsAvailableGt: z.optional(z.number()),
    endTime: z.optional(z.string()),
    expand: z.optional(z.string()),
    expiryDateAfter: z.optional(z.string()),
    expiryDateBefore: z.optional(z.string()),
    idQueryParameter: z.optional(z.string()),
    limit: z.optional(z.int()),
    offset: z.optional(z.int()),
    order: z.optional(GetWalletsIdTransactionsQueryParamOrder$outboundSchema),
    priority: z.optional(z.int()),
    referenceId: z.optional(z.string()),
    referenceType: z.optional(z.string()),
    sort: z.optional(z.string()),
    startTime: z.optional(z.string()),
    status: z.optional(GetWalletsIdTransactionsQueryParamStatus$outboundSchema),
    transactionReason: z.optional(TransactionReason$outboundSchema),
    transactionStatus: z.optional(TransactionStatus$outboundSchema),
    type: z.optional(Type$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      creditsAvailableGt: "credits_available_gt",
      endTime: "end_time",
      expiryDateAfter: "expiry_date_after",
      expiryDateBefore: "expiry_date_before",
      referenceId: "reference_id",
      referenceType: "reference_type",
      startTime: "start_time",
      transactionReason: "transaction_reason",
      transactionStatus: "transaction_status",
    });
  }),
);

export function getWalletsIdTransactionsRequestToJSON(
  getWalletsIdTransactionsRequest: GetWalletsIdTransactionsRequest,
): string {
  return JSON.stringify(
    GetWalletsIdTransactionsRequest$outboundSchema.parse(
      getWalletsIdTransactionsRequest,
    ),
  );
}
