/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d4e8c02baccf
 */

import * as z from "zod/v4-mini";

export type GetWalletsIdRequest = {
  /**
   * Wallet ID
   */
  id: string;
};

/** @internal */
export type GetWalletsIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWalletsIdRequest$outboundSchema: z.ZodMiniType<
  GetWalletsIdRequest$Outbound,
  GetWalletsIdRequest
> = z.object({
  id: z.string(),
});

export function getWalletsIdRequestToJSON(
  getWalletsIdRequest: GetWalletsIdRequest,
): string {
  return JSON.stringify(
    GetWalletsIdRequest$outboundSchema.parse(getWalletsIdRequest),
  );
}
