/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7eef95dd13d3
 */

import * as z from "zod/v4-mini";

export type PostCreditnotesIdFinalizeRequest = {
  /**
   * Credit note ID
   */
  id: string;
};

/** @internal */
export type PostCreditnotesIdFinalizeRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostCreditnotesIdFinalizeRequest$outboundSchema: z.ZodMiniType<
  PostCreditnotesIdFinalizeRequest$Outbound,
  PostCreditnotesIdFinalizeRequest
> = z.object({
  id: z.string(),
});

export function postCreditnotesIdFinalizeRequestToJSON(
  postCreditnotesIdFinalizeRequest: PostCreditnotesIdFinalizeRequest,
): string {
  return JSON.stringify(
    PostCreditnotesIdFinalizeRequest$outboundSchema.parse(
      postCreditnotesIdFinalizeRequest,
    ),
  );
}
