/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8bcd03c14098
 */

import * as z from "zod/v4-mini";

export type PostPaymentsIdProcessRequest = {
  /**
   * Payment ID
   */
  id: string;
};

/** @internal */
export type PostPaymentsIdProcessRequest$Outbound = {
  id: string;
};

/** @internal */
export const PostPaymentsIdProcessRequest$outboundSchema: z.ZodMiniType<
  PostPaymentsIdProcessRequest$Outbound,
  PostPaymentsIdProcessRequest
> = z.object({
  id: z.string(),
});

export function postPaymentsIdProcessRequestToJSON(
  postPaymentsIdProcessRequest: PostPaymentsIdProcessRequest,
): string {
  return JSON.stringify(
    PostPaymentsIdProcessRequest$outboundSchema.parse(
      postPaymentsIdProcessRequest,
    ),
  );
}
