/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bf64b623a2fb
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type PostTasksScheduledIdRunRequest = {
  /**
   * Scheduled Task ID
   */
  id: string;
  /**
   * Optional start and end time for custom range
   */
  body?: components.DtoTriggerForceRunRequest | undefined;
};

/** @internal */
export type PostTasksScheduledIdRunRequest$Outbound = {
  id: string;
  body?: components.DtoTriggerForceRunRequest$Outbound | undefined;
};

/** @internal */
export const PostTasksScheduledIdRunRequest$outboundSchema: z.ZodMiniType<
  PostTasksScheduledIdRunRequest$Outbound,
  PostTasksScheduledIdRunRequest
> = z.object({
  id: z.string(),
  body: z.optional(components.DtoTriggerForceRunRequest$outboundSchema),
});

export function postTasksScheduledIdRunRequestToJSON(
  postTasksScheduledIdRunRequest: PostTasksScheduledIdRunRequest,
): string {
  return JSON.stringify(
    PostTasksScheduledIdRunRequest$outboundSchema.parse(
      postTasksScheduledIdRunRequest,
    ),
  );
}
