/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 86debfccaa7f
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PutCustomersIdRequest = {
  /**
   * Customer ID
   */
  id: string;
  /**
   * Customer
   */
  body: models.DtoUpdateCustomerRequest;
};

/** @internal */
export type PutCustomersIdRequest$Outbound = {
  id: string;
  body: models.DtoUpdateCustomerRequest$Outbound;
};

/** @internal */
export const PutCustomersIdRequest$outboundSchema: z.ZodMiniType<
  PutCustomersIdRequest$Outbound,
  PutCustomersIdRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateCustomerRequest$outboundSchema,
});

export function putCustomersIdRequestToJSON(
  putCustomersIdRequest: PutCustomersIdRequest,
): string {
  return JSON.stringify(
    PutCustomersIdRequest$outboundSchema.parse(putCustomersIdRequest),
  );
}
