/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: f9088524b568
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PutEntitlementsIdRequest = {
  /**
   * Entitlement ID
   */
  id: string;
  /**
   * Entitlement configuration
   */
  body: models.DtoUpdateEntitlementRequest;
};

/** @internal */
export type PutEntitlementsIdRequest$Outbound = {
  id: string;
  body: models.DtoUpdateEntitlementRequest$Outbound;
};

/** @internal */
export const PutEntitlementsIdRequest$outboundSchema: z.ZodMiniType<
  PutEntitlementsIdRequest$Outbound,
  PutEntitlementsIdRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateEntitlementRequest$outboundSchema,
});

export function putEntitlementsIdRequestToJSON(
  putEntitlementsIdRequest: PutEntitlementsIdRequest,
): string {
  return JSON.stringify(
    PutEntitlementsIdRequest$outboundSchema.parse(putEntitlementsIdRequest),
  );
}
