/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: dc68c531f4f3
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type PutEnvironmentsIdRequest = {
  /**
   * Environment ID
   */
  id: string;
  /**
   * Environment
   */
  body: models.DtoUpdateEnvironmentRequest;
};

/** @internal */
export type PutEnvironmentsIdRequest$Outbound = {
  id: string;
  body: models.DtoUpdateEnvironmentRequest$Outbound;
};

/** @internal */
export const PutEnvironmentsIdRequest$outboundSchema: z.ZodMiniType<
  PutEnvironmentsIdRequest$Outbound,
  PutEnvironmentsIdRequest
> = z.object({
  id: z.string(),
  body: models.DtoUpdateEnvironmentRequest$outboundSchema,
});

export function putEnvironmentsIdRequestToJSON(
  putEnvironmentsIdRequest: PutEnvironmentsIdRequest,
): string {
  return JSON.stringify(
    PutEnvironmentsIdRequest$outboundSchema.parse(putEnvironmentsIdRequest),
  );
}
