/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8d9f1ae30d97
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type PutInvoicesIdRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Invoice Update Request
   */
  body: components.DtoUpdateInvoiceRequest;
};

/** @internal */
export type PutInvoicesIdRequest$Outbound = {
  id: string;
  body: components.DtoUpdateInvoiceRequest$Outbound;
};

/** @internal */
export const PutInvoicesIdRequest$outboundSchema: z.ZodMiniType<
  PutInvoicesIdRequest$Outbound,
  PutInvoicesIdRequest
> = z.object({
  id: z.string(),
  body: components.DtoUpdateInvoiceRequest$outboundSchema,
});

export function putInvoicesIdRequestToJSON(
  putInvoicesIdRequest: PutInvoicesIdRequest,
): string {
  return JSON.stringify(
    PutInvoicesIdRequest$outboundSchema.parse(putInvoicesIdRequest),
  );
}
