/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c42c2f0d60ca
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type PutInvoicesIdPaymentRequest = {
  /**
   * Invoice ID
   */
  id: string;
  /**
   * Payment Status Update Request
   */
  body: components.DtoUpdatePaymentStatusRequest;
};

/** @internal */
export type PutInvoicesIdPaymentRequest$Outbound = {
  id: string;
  body: components.DtoUpdatePaymentStatusRequest$Outbound;
};

/** @internal */
export const PutInvoicesIdPaymentRequest$outboundSchema: z.ZodMiniType<
  PutInvoicesIdPaymentRequest$Outbound,
  PutInvoicesIdPaymentRequest
> = z.object({
  id: z.string(),
  body: components.DtoUpdatePaymentStatusRequest$outboundSchema,
});

export function putInvoicesIdPaymentRequestToJSON(
  putInvoicesIdPaymentRequest: PutInvoicesIdPaymentRequest,
): string {
  return JSON.stringify(
    PutInvoicesIdPaymentRequest$outboundSchema.parse(
      putInvoicesIdPaymentRequest,
    ),
  );
}
