"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: a006ab05f583

from __future__ import annotations
from typing import Literal


DtoEntitlementSourceEntityType = Literal[
    "plan",
    "addon",
    "subscription",
]
