"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 89d74709cca7

from __future__ import annotations
from flexprice.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoEventCountPointTypedDict(TypedDict):
    event_count: NotRequired[int]
    timestamp: NotRequired[str]


class DtoEventCountPoint(BaseModel):
    event_count: Optional[int] = None

    timestamp: Optional[str] = None
