"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ddf7a1157dc9

from __future__ import annotations
from typing import Literal


TypesSecretProvider = Literal[
    "flexprice",
    "stripe",
    "s3",
    "hubspot",
    "razorpay",
    "chargebee",
    "quickbooks",
    "nomod",
]
