"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 58eb769c5425

from __future__ import annotations
from flexprice.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TypesAutoTopupTypedDict(TypedDict):
    amount: NotRequired[float]
    enabled: NotRequired[bool]
    invoicing: NotRequired[bool]
    threshold: NotRequired[float]


class TypesAutoTopup(BaseModel):
    amount: Optional[float] = None

    enabled: Optional[bool] = None

    invoicing: Optional[bool] = None

    threshold: Optional[float] = None
