"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1e053093b37f

from __future__ import annotations
from typing import Literal


TypesCollectionMethod = Literal[
    "charge_automatically",
    "send_invoice",
]
