"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 70f4a8a1d515

from __future__ import annotations
from typing import Literal


TypesCouponType = Literal[
    "fixed",
    "percentage",
]
