"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 04aabc37ecf2

from __future__ import annotations
from typing import Literal


TypesInvoiceBilling = Literal[
    "invoice_to_parent",
    "invoice_to_self",
]
