"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .types_walletstatus import TypesWalletStatus
from flexprice.types import BaseModel
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


TypesWalletFilterOrder = Literal[
    "asc",
    "desc",
]


class TypesWalletFilterTypedDict(TypedDict):
    alert_enabled: NotRequired[bool]
    expand: NotRequired[str]
    limit: NotRequired[int]
    offset: NotRequired[int]
    order: NotRequired[TypesWalletFilterOrder]
    sort: NotRequired[str]
    status: NotRequired[TypesWalletStatus]
    wallet_ids: NotRequired[List[str]]


class TypesWalletFilter(BaseModel):
    alert_enabled: Optional[bool] = None

    expand: Optional[str] = None

    limit: Optional[int] = None

    offset: Optional[int] = None

    order: Optional[TypesWalletFilterOrder] = None

    sort: Optional[str] = None

    status: Optional[TypesWalletStatus] = None

    wallet_ids: Optional[List[str]] = None
