"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 33ebdbb12c40

from __future__ import annotations
from typing import Literal


TypesScheduledTaskEntityType = Literal[
    "events",
    "invoice",
    "credit_topups",
    "credit_usage",
]
