"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0b26f430df6b

from __future__ import annotations
from typing import Literal


TypesPaymentMethodType = Literal[
    "CARD",
    "ACH",
    "OFFLINE",
    "CREDITS",
    "PAYMENT_LINK",
]
