/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c99d231d30e8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  TypesTaxRateEntityType,
  TypesTaxRateEntityType$outboundSchema,
} from "./typestaxrateentitytype.js";

export type DtoCreateTaxAssociationRequest = {
  autoApply?: boolean | undefined;
  currency?: string | undefined;
  entityId: string;
  entityType: TypesTaxRateEntityType;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  taxRateCode: string;
};

/** @internal */
export type DtoCreateTaxAssociationRequest$Outbound = {
  auto_apply?: boolean | undefined;
  currency?: string | undefined;
  entity_id: string;
  entity_type: string;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  tax_rate_code: string;
};

/** @internal */
export const DtoCreateTaxAssociationRequest$outboundSchema: z.ZodMiniType<
  DtoCreateTaxAssociationRequest$Outbound,
  DtoCreateTaxAssociationRequest
> = z.pipe(
  z.object({
    autoApply: z.optional(z.boolean()),
    currency: z.optional(z.string()),
    entityId: z.string(),
    entityType: TypesTaxRateEntityType$outboundSchema,
    metadata: z.optional(z.record(z.string(), z.string())),
    priority: z.optional(z.int()),
    taxRateCode: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      autoApply: "auto_apply",
      entityId: "entity_id",
      entityType: "entity_type",
      taxRateCode: "tax_rate_code",
    });
  }),
);

export function dtoCreateTaxAssociationRequestToJSON(
  dtoCreateTaxAssociationRequest: DtoCreateTaxAssociationRequest,
): string {
  return JSON.stringify(
    DtoCreateTaxAssociationRequest$outboundSchema.parse(
      dtoCreateTaxAssociationRequest,
    ),
  );
}
