/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: b7a96924938f
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  DtoCreatePriceTier,
  DtoCreatePriceTier$Outbound,
  DtoCreatePriceTier$outboundSchema,
} from "./dtocreatepricetier.js";

export type DtoPriceUnitConfig = {
  amount?: string | undefined;
  priceUnit: string;
  priceUnitTiers?: Array<DtoCreatePriceTier> | undefined;
};

/** @internal */
export type DtoPriceUnitConfig$Outbound = {
  amount?: string | undefined;
  price_unit: string;
  price_unit_tiers?: Array<DtoCreatePriceTier$Outbound> | undefined;
};

/** @internal */
export const DtoPriceUnitConfig$outboundSchema: z.ZodMiniType<
  DtoPriceUnitConfig$Outbound,
  DtoPriceUnitConfig
> = z.pipe(
  z.object({
    amount: z.optional(z.string()),
    priceUnit: z.string(),
    priceUnitTiers: z.optional(z.array(DtoCreatePriceTier$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      priceUnit: "price_unit",
      priceUnitTiers: "price_unit_tiers",
    });
  }),
);

export function dtoPriceUnitConfigToJSON(
  dtoPriceUnitConfig: DtoPriceUnitConfig,
): string {
  return JSON.stringify(
    DtoPriceUnitConfig$outboundSchema.parse(dtoPriceUnitConfig),
  );
}
