/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c7da970ea089
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DtoAddonResponse,
  DtoAddonResponse$inboundSchema,
} from "./dtoaddonresponse.js";
import {
  DtoGroupResponse,
  DtoGroupResponse$inboundSchema,
} from "./dtogroupresponse.js";
import {
  DtoMeterResponse,
  DtoMeterResponse$inboundSchema,
} from "./dtometerresponse.js";
import {
  DtoPlanResponse,
  DtoPlanResponse$inboundSchema,
} from "./dtoplanresponse.js";
import {
  DtoPriceUnitResponse,
  DtoPriceUnitResponse$inboundSchema,
} from "./dtopriceunitresponse.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PriceJSONBTransformQuantity,
  PriceJSONBTransformQuantity$inboundSchema,
} from "./pricejsonbtransformquantity.js";
import {
  PricePriceTier,
  PricePriceTier$inboundSchema,
} from "./pricepricetier.js";
import {
  TypesBillingCadence,
  TypesBillingCadence$inboundSchema,
} from "./typesbillingcadence.js";
import {
  TypesBillingModel,
  TypesBillingModel$inboundSchema,
} from "./typesbillingmodel.js";
import {
  TypesBillingPeriod,
  TypesBillingPeriod$inboundSchema,
} from "./typesbillingperiod.js";
import {
  TypesBillingTier,
  TypesBillingTier$inboundSchema,
} from "./typesbillingtier.js";
import {
  TypesInvoiceCadence,
  TypesInvoiceCadence$inboundSchema,
} from "./typesinvoicecadence.js";
import {
  TypesPriceEntityType,
  TypesPriceEntityType$inboundSchema,
} from "./typespriceentitytype.js";
import {
  TypesPriceType,
  TypesPriceType$inboundSchema,
} from "./typespricetype.js";
import {
  TypesPriceUnitType,
  TypesPriceUnitType$inboundSchema,
} from "./typespriceunittype.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";

export type DtoPriceResponse = {
  addon?: DtoAddonResponse | undefined;
  /**
   * Amount stored in main currency units (e.g., dollars, not cents)
   *
   * @remarks
   * For USD: 12.50 means $12.50
   */
  amount?: string | undefined;
  billingCadence?: TypesBillingCadence | undefined;
  billingModel?: TypesBillingModel | undefined;
  billingPeriod?: TypesBillingPeriod | undefined;
  /**
   * BillingPeriodCount is the count of the billing period ex 1, 3, 6, 12
   */
  billingPeriodCount?: number | undefined;
  /**
   * ConversionRate is the rate of the price unit to the base currency
   *
   * @remarks
   * For BTC: 1 BTC = 100000000 USD
   */
  conversionRate?: string | undefined;
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  /**
   * Currency 3 digit ISO currency code in lowercase ex usd, eur, gbp
   */
  currency?: string | undefined;
  /**
   * Description of the price
   */
  description?: string | undefined;
  /**
   * DisplayAmount is the formatted amount with currency symbol
   *
   * @remarks
   * For USD: $12.50
   */
  displayAmount?: string | undefined;
  /**
   * DisplayName is the name of the price
   */
  displayName?: string | undefined;
  /**
   * DisplayPriceUnitAmount is the formatted amount with price unit symbol
   *
   * @remarks
   * For BTC: 0.00000001 BTC
   */
  displayPriceUnitAmount?: string | undefined;
  /**
   * EndDate is the end date of the price
   */
  endDate?: string | undefined;
  /**
   * EntityID holds the value of the "entity_id" field.
   */
  entityId?: string | undefined;
  entityType?: TypesPriceEntityType | undefined;
  /**
   * EnvironmentID is the environment identifier for the price
   */
  environmentId?: string | undefined;
  group?: DtoGroupResponse | undefined;
  /**
   * GroupID references the group this price belongs to
   */
  groupId?: string | undefined;
  /**
   * ID uuid identifier for the price
   */
  id?: string | undefined;
  invoiceCadence?: TypesInvoiceCadence | undefined;
  /**
   * LookupKey used for looking up the price in the database
   */
  lookupKey?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: DtoMeterResponse | undefined;
  /**
   * MeterID is the id of the meter for usage based pricing
   */
  meterId?: string | undefined;
  /**
   * MinQuantity is the minimum quantity of the price
   */
  minQuantity?: number | undefined;
  /**
   * ParentPriceID references the root price (always set for price lineage tracking)
   */
  parentPriceId?: string | undefined;
  plan?: DtoPlanResponse | undefined;
  /**
   * PriceUnit 3 digit ISO currency code in lowercase ex btc
   *
   * @remarks
   * For BTC: btc
   */
  priceUnit?: string | undefined;
  /**
   * PriceUnitAmount is the amount stored in price unit
   *
   * @remarks
   * For BTC: 0.00000001 means 0.00000001 BTC
   */
  priceUnitAmount?: string | undefined;
  /**
   * PriceUnitID is the id of the price unit
   */
  priceUnitId?: string | undefined;
  /**
   * PriceUnitTiers are the tiers for the price unit
   */
  priceUnitTiers?: Array<PricePriceTier> | undefined;
  priceUnitType?: TypesPriceUnitType | undefined;
  pricingUnit?: DtoPriceUnitResponse | undefined;
  /**
   * StartDate is the start date of the price
   */
  startDate?: string | undefined;
  status?: TypesStatus | undefined;
  tenantId?: string | undefined;
  tierMode?: TypesBillingTier | undefined;
  tiers?: Array<PricePriceTier> | undefined;
  transformQuantity?: PriceJSONBTransformQuantity | undefined;
  /**
   * TrialPeriod is the number of days for the trial period
   *
   * @remarks
   * Note: This is only applicable for recurring prices (BILLING_CADENCE_RECURRING)
   */
  trialPeriod?: number | undefined;
  type?: TypesPriceType | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoPriceResponse$inboundSchema: z.ZodMiniType<
  DtoPriceResponse,
  unknown
> = z.pipe(
  z.object({
    addon: types.optional(z.lazy(() => DtoAddonResponse$inboundSchema)),
    amount: types.optional(types.string()),
    billing_cadence: types.optional(TypesBillingCadence$inboundSchema),
    billing_model: types.optional(TypesBillingModel$inboundSchema),
    billing_period: types.optional(TypesBillingPeriod$inboundSchema),
    billing_period_count: types.optional(types.number()),
    conversion_rate: types.optional(types.string()),
    created_at: types.optional(types.string()),
    created_by: types.optional(types.string()),
    currency: types.optional(types.string()),
    description: types.optional(types.string()),
    display_amount: types.optional(types.string()),
    display_name: types.optional(types.string()),
    display_price_unit_amount: types.optional(types.string()),
    end_date: types.optional(types.string()),
    entity_id: types.optional(types.string()),
    entity_type: types.optional(TypesPriceEntityType$inboundSchema),
    environment_id: types.optional(types.string()),
    group: types.optional(DtoGroupResponse$inboundSchema),
    group_id: types.optional(types.string()),
    id: types.optional(types.string()),
    invoice_cadence: types.optional(TypesInvoiceCadence$inboundSchema),
    lookup_key: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), types.string())),
    meter: types.optional(DtoMeterResponse$inboundSchema),
    meter_id: types.optional(types.string()),
    min_quantity: types.optional(types.number()),
    parent_price_id: types.optional(types.string()),
    plan: types.optional(z.lazy(() => DtoPlanResponse$inboundSchema)),
    price_unit: types.optional(types.string()),
    price_unit_amount: types.optional(types.string()),
    price_unit_id: types.optional(types.string()),
    price_unit_tiers: types.optional(z.array(PricePriceTier$inboundSchema)),
    price_unit_type: types.optional(TypesPriceUnitType$inboundSchema),
    pricing_unit: types.optional(DtoPriceUnitResponse$inboundSchema),
    start_date: types.optional(types.string()),
    status: types.optional(TypesStatus$inboundSchema),
    tenant_id: types.optional(types.string()),
    tier_mode: types.optional(TypesBillingTier$inboundSchema),
    tiers: types.optional(z.array(PricePriceTier$inboundSchema)),
    transform_quantity: types.optional(
      PriceJSONBTransformQuantity$inboundSchema,
    ),
    trial_period: types.optional(types.number()),
    type: types.optional(TypesPriceType$inboundSchema),
    updated_at: types.optional(types.string()),
    updated_by: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "billing_cadence": "billingCadence",
      "billing_model": "billingModel",
      "billing_period": "billingPeriod",
      "billing_period_count": "billingPeriodCount",
      "conversion_rate": "conversionRate",
      "created_at": "createdAt",
      "created_by": "createdBy",
      "display_amount": "displayAmount",
      "display_name": "displayName",
      "display_price_unit_amount": "displayPriceUnitAmount",
      "end_date": "endDate",
      "entity_id": "entityId",
      "entity_type": "entityType",
      "environment_id": "environmentId",
      "group_id": "groupId",
      "invoice_cadence": "invoiceCadence",
      "lookup_key": "lookupKey",
      "meter_id": "meterId",
      "min_quantity": "minQuantity",
      "parent_price_id": "parentPriceId",
      "price_unit": "priceUnit",
      "price_unit_amount": "priceUnitAmount",
      "price_unit_id": "priceUnitId",
      "price_unit_tiers": "priceUnitTiers",
      "price_unit_type": "priceUnitType",
      "pricing_unit": "pricingUnit",
      "start_date": "startDate",
      "tenant_id": "tenantId",
      "tier_mode": "tierMode",
      "transform_quantity": "transformQuantity",
      "trial_period": "trialPeriod",
      "updated_at": "updatedAt",
      "updated_by": "updatedBy",
    });
  }),
);

export function dtoPriceResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoPriceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoPriceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoPriceResponse' from JSON`,
  );
}
