/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8d2bdd0129ec
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesResetUsage = {
  BillingPeriod: "BILLING_PERIOD",
  Never: "NEVER",
} as const;
export type TypesResetUsage = OpenEnum<typeof TypesResetUsage>;

/** @internal */
export const TypesResetUsage$inboundSchema: z.ZodMiniType<
  TypesResetUsage,
  unknown
> = openEnums.inboundSchema(TypesResetUsage);
/** @internal */
export const TypesResetUsage$outboundSchema: z.ZodMiniType<
  string,
  TypesResetUsage
> = openEnums.outboundSchema(TypesResetUsage);
