/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3fa3694b128d
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesSecretType = {
  PrivateKey: "private_key",
  PublishableKey: "publishable_key",
  Integration: "integration",
} as const;
export type TypesSecretType = OpenEnum<typeof TypesSecretType>;

/** @internal */
export const TypesSecretType$inboundSchema: z.ZodMiniType<
  TypesSecretType,
  unknown
> = openEnums.inboundSchema(TypesSecretType);
/** @internal */
export const TypesSecretType$outboundSchema: z.ZodMiniType<
  string,
  TypesSecretType
> = openEnums.outboundSchema(TypesSecretType);
