/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 12f2d0f26ed6
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesProrationBehavior = {
  CreateProrations: "create_prorations",
  None: "none",
} as const;
export type TypesProrationBehavior = OpenEnum<typeof TypesProrationBehavior>;

/** @internal */
export const TypesProrationBehavior$inboundSchema: z.ZodMiniType<
  TypesProrationBehavior,
  unknown
> = openEnums.inboundSchema(TypesProrationBehavior);
/** @internal */
export const TypesProrationBehavior$outboundSchema: z.ZodMiniType<
  string,
  TypesProrationBehavior
> = openEnums.outboundSchema(TypesProrationBehavior);
