/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 736c12118ab0
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

export const TypesWalletConfigPriceType = {
  All: "ALL",
  Usage: "USAGE",
  Fixed: "FIXED",
} as const;
export type TypesWalletConfigPriceType = OpenEnum<
  typeof TypesWalletConfigPriceType
>;

/** @internal */
export const TypesWalletConfigPriceType$inboundSchema: z.ZodMiniType<
  TypesWalletConfigPriceType,
  unknown
> = openEnums.inboundSchema(TypesWalletConfigPriceType);
/** @internal */
export const TypesWalletConfigPriceType$outboundSchema: z.ZodMiniType<
  string,
  TypesWalletConfigPriceType
> = openEnums.outboundSchema(TypesWalletConfigPriceType);
