/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 60b9cca5ded1
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TypesAlertSettings,
  TypesAlertSettings$inboundSchema,
} from "./typesalertsettings.js";

export type TypesAlertInfo = {
  alertSettings?: TypesAlertSettings | undefined;
  timestamp?: string | undefined;
  valueAtTime?: number | undefined;
};

/** @internal */
export const TypesAlertInfo$inboundSchema: z.ZodMiniType<
  TypesAlertInfo,
  unknown
> = z.pipe(
  z.object({
    alert_settings: types.optional(TypesAlertSettings$inboundSchema),
    timestamp: types.optional(types.string()),
    value_at_time: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "alert_settings": "alertSettings",
      "value_at_time": "valueAtTime",
    });
  }),
);

export function typesAlertInfoFromJSON(
  jsonString: string,
): SafeParseResult<TypesAlertInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypesAlertInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypesAlertInfo' from JSON`,
  );
}
