/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3b1264d3a355
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TypesSecretProvider,
  TypesSecretProvider$inboundSchema,
} from "./typessecretprovider.js";
import { TypesStatus, TypesStatus$inboundSchema } from "./typesstatus.js";
import {
  TypesSyncConfig,
  TypesSyncConfig$inboundSchema,
} from "./typessyncconfig.js";

export type DtoConnectionResponse = {
  createdAt?: string | undefined;
  createdBy?: string | undefined;
  environmentId?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  name?: string | undefined;
  providerType?: TypesSecretProvider | undefined;
  status?: TypesStatus | undefined;
  syncConfig?: TypesSyncConfig | undefined;
  tenantId?: string | undefined;
  updatedAt?: string | undefined;
  updatedBy?: string | undefined;
};

/** @internal */
export const DtoConnectionResponse$inboundSchema: z.ZodMiniType<
  DtoConnectionResponse,
  unknown
> = z.pipe(
  z.object({
    created_at: types.optional(types.string()),
    created_by: types.optional(types.string()),
    environment_id: types.optional(types.string()),
    id: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), z.any())),
    name: types.optional(types.string()),
    provider_type: types.optional(TypesSecretProvider$inboundSchema),
    status: types.optional(TypesStatus$inboundSchema),
    sync_config: types.optional(TypesSyncConfig$inboundSchema),
    tenant_id: types.optional(types.string()),
    updated_at: types.optional(types.string()),
    updated_by: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
      "created_by": "createdBy",
      "environment_id": "environmentId",
      "provider_type": "providerType",
      "sync_config": "syncConfig",
      "tenant_id": "tenantId",
      "updated_at": "updatedAt",
      "updated_by": "updatedBy",
    });
  }),
);

export function dtoConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoConnectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoConnectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoConnectionResponse' from JSON`,
  );
}
