/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$inboundSchema,
} from "./dtoentitlementresponse.js";

export type DtoCreateBulkEntitlementResponse = {
  items?: Array<DtoEntitlementResponse> | undefined;
};

/** @internal */
export const DtoCreateBulkEntitlementResponse$inboundSchema: z.ZodMiniType<
  DtoCreateBulkEntitlementResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoEntitlementResponse$inboundSchema)),
});

export function dtoCreateBulkEntitlementResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoCreateBulkEntitlementResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoCreateBulkEntitlementResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoCreateBulkEntitlementResponse' from JSON`,
  );
}
