/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a20ead762e3e
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  TypesEntityType,
  TypesEntityType$outboundSchema,
} from "./typesentitytype.js";
import {
  TypesFileType,
  TypesFileType$outboundSchema,
} from "./typesfiletype.js";
import {
  TypesTaskType,
  TypesTaskType$outboundSchema,
} from "./typestasktype.js";

export type DtoCreateTaskRequest = {
  entityType: TypesEntityType;
  fileName?: string | undefined;
  fileType: TypesFileType;
  fileUrl: string;
  metadata?: { [k: string]: any } | undefined;
  taskType: TypesTaskType;
};

/** @internal */
export type DtoCreateTaskRequest$Outbound = {
  entity_type: string;
  file_name?: string | undefined;
  file_type: string;
  file_url: string;
  metadata?: { [k: string]: any } | undefined;
  task_type: string;
};

/** @internal */
export const DtoCreateTaskRequest$outboundSchema: z.ZodMiniType<
  DtoCreateTaskRequest$Outbound,
  DtoCreateTaskRequest
> = z.pipe(
  z.object({
    entityType: TypesEntityType$outboundSchema,
    fileName: z.optional(z.string()),
    fileType: TypesFileType$outboundSchema,
    fileUrl: z.string(),
    metadata: z.optional(z.record(z.string(), z.any())),
    taskType: TypesTaskType$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      entityType: "entity_type",
      fileName: "file_name",
      fileType: "file_type",
      fileUrl: "file_url",
      taskType: "task_type",
    });
  }),
);

export function dtoCreateTaskRequestToJSON(
  dtoCreateTaskRequest: DtoCreateTaskRequest,
): string {
  return JSON.stringify(
    DtoCreateTaskRequest$outboundSchema.parse(dtoCreateTaskRequest),
  );
}
