/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 12001e4c8742
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoUsageAnalyticItem,
  DtoUsageAnalyticItem$inboundSchema,
} from "./dtousageanalyticitem.js";

export type DtoGetUsageAnalyticsResponse = {
  currency?: string | undefined;
  items?: Array<DtoUsageAnalyticItem> | undefined;
  totalCost?: string | undefined;
};

/** @internal */
export const DtoGetUsageAnalyticsResponse$inboundSchema: z.ZodMiniType<
  DtoGetUsageAnalyticsResponse,
  unknown
> = z.pipe(
  z.object({
    currency: types.optional(types.string()),
    items: types.optional(z.array(DtoUsageAnalyticItem$inboundSchema)),
    total_cost: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_cost": "totalCost",
    });
  }),
);

export function dtoGetUsageAnalyticsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoGetUsageAnalyticsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoGetUsageAnalyticsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoGetUsageAnalyticsResponse' from JSON`,
  );
}
