/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoEntitlementResponse,
  DtoEntitlementResponse$inboundSchema,
} from "./dtoentitlementresponse.js";
import {
  TypesPaginationResponse,
  TypesPaginationResponse$inboundSchema,
} from "./typespaginationresponse.js";

export type DtoListEntitlementsResponse = {
  items?: Array<DtoEntitlementResponse> | undefined;
  pagination?: TypesPaginationResponse | undefined;
};

/** @internal */
export const DtoListEntitlementsResponse$inboundSchema: z.ZodMiniType<
  DtoListEntitlementsResponse,
  unknown
> = z.object({
  items: types.optional(z.array(DtoEntitlementResponse$inboundSchema)),
  pagination: types.optional(TypesPaginationResponse$inboundSchema),
});

export function dtoListEntitlementsResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoListEntitlementsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoListEntitlementsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoListEntitlementsResponse' from JSON`,
  );
}
