/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 08c2b7e0dcc8
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DtoTenantBillingDetails,
  DtoTenantBillingDetails$inboundSchema,
} from "./dtotenantbillingdetails.js";

export type DtoTenantResponse = {
  billingDetails?: DtoTenantBillingDetails | undefined;
  createdAt?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: string | undefined;
  updatedAt?: string | undefined;
};

/** @internal */
export const DtoTenantResponse$inboundSchema: z.ZodMiniType<
  DtoTenantResponse,
  unknown
> = z.pipe(
  z.object({
    billing_details: types.optional(DtoTenantBillingDetails$inboundSchema),
    created_at: types.optional(types.string()),
    id: types.optional(types.string()),
    metadata: types.optional(z.record(z.string(), types.string())),
    name: types.optional(types.string()),
    status: types.optional(types.string()),
    updated_at: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "billing_details": "billingDetails",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function dtoTenantResponseFromJSON(
  jsonString: string,
): SafeParseResult<DtoTenantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DtoTenantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DtoTenantResponse' from JSON`,
  );
}
