/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 50cd83fb637a
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const TypesEntitlementEntityType = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
  Addon: "ADDON",
} as const;
export type TypesEntitlementEntityType = OpenEnum<
  typeof TypesEntitlementEntityType
>;

/** @internal */
export const TypesEntitlementEntityType$inboundSchema: z.ZodMiniType<
  TypesEntitlementEntityType,
  unknown
> = openEnums.inboundSchema(TypesEntitlementEntityType);
/** @internal */
export const TypesEntitlementEntityType$outboundSchema: z.ZodMiniType<
  string,
  TypesEntitlementEntityType
> = openEnums.outboundSchema(TypesEntitlementEntityType);
