/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: c296d27c0ba5
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const TypesBillingCadence = {
  Recurring: "RECURRING",
  Onetime: "ONETIME",
} as const;
export type TypesBillingCadence = OpenEnum<typeof TypesBillingCadence>;

/** @internal */
export const TypesBillingCadence$inboundSchema: z.ZodMiniType<
  TypesBillingCadence,
  unknown
> = openEnums.inboundSchema(TypesBillingCadence);
/** @internal */
export const TypesBillingCadence$outboundSchema: z.ZodMiniType<
  string,
  TypesBillingCadence
> = openEnums.outboundSchema(TypesBillingCadence);
