"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ea49115a14b7

from __future__ import annotations
from flexprice.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DtoUpdatePriceUnitRequestTypedDict(TypedDict):
    conversion_rate: NotRequired[str]
    name: NotRequired[str]
    precision: NotRequired[int]
    symbol: NotRequired[str]


class DtoUpdatePriceUnitRequest(BaseModel):
    conversion_rate: Optional[str] = None

    name: Optional[str] = None

    precision: Optional[int] = None

    symbol: Optional[str] = None
