"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d627296855e0

from __future__ import annotations
from flexprice.types import BaseModel
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class DtoAddAddonToSubscriptionRequestTypedDict(TypedDict):
    addon_id: str
    end_date: NotRequired[str]
    metadata: NotRequired[Dict[str, Any]]
    start_date: NotRequired[str]


class DtoAddAddonToSubscriptionRequest(BaseModel):
    addon_id: str

    end_date: Optional[str] = None

    metadata: Optional[Dict[str, Any]] = None

    start_date: Optional[str] = None
