"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: f8033b01bf0a

from __future__ import annotations
from .dto_usageanalyticitem import DtoUsageAnalyticItem, DtoUsageAnalyticItemTypedDict
from flexprice.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DtoGetUsageAnalyticsResponseTypedDict(TypedDict):
    currency: NotRequired[str]
    items: NotRequired[List[DtoUsageAnalyticItemTypedDict]]
    total_cost: NotRequired[str]


class DtoGetUsageAnalyticsResponse(BaseModel):
    currency: Optional[str] = None

    items: Optional[List[DtoUsageAnalyticItem]] = None

    total_cost: Optional[str] = None
