"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 38cc67339a30

from __future__ import annotations
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, QueryParamMetadata
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


GetCreditgrantsQueryParamOrder = Literal[
    "asc",
    "desc",
]


Scope = Literal[
    "PLAN",
    "SUBSCRIPTION",
]


GetCreditgrantsQueryParamStatus = Literal[
    "published",
    "deleted",
    "archived",
]


class GetCreditgrantsRequestTypedDict(TypedDict):
    end_time: NotRequired[str]
    expand: NotRequired[str]
    limit: NotRequired[int]
    offset: NotRequired[int]
    order: NotRequired[GetCreditgrantsQueryParamOrder]
    plan_ids: NotRequired[List[str]]
    r"""Specific filters for credit grants"""
    scope: NotRequired[Scope]
    sort: NotRequired[str]
    start_time: NotRequired[str]
    status: NotRequired[GetCreditgrantsQueryParamStatus]
    subscription_ids: NotRequired[List[str]]


class GetCreditgrantsRequest(BaseModel):
    end_time: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    expand: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    order: Annotated[
        Optional[GetCreditgrantsQueryParamOrder],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    plan_ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
    r"""Specific filters for credit grants"""

    scope: Annotated[
        Optional[Scope],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    sort: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    start_time: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    status: Annotated[
        Optional[GetCreditgrantsQueryParamStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    subscription_ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=False)),
    ] = None
