"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0fa2ee1933f8

from __future__ import annotations
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetAddonsIDEntitlementsRequestTypedDict(TypedDict):
    id: str
    r"""Addon ID"""


class GetAddonsIDEntitlementsRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Addon ID"""
