"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 5c3ee8112c47

from __future__ import annotations
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostWebhooksQuickbooksTenantIDEnvironmentIDRequestTypedDict(TypedDict):
    tenant_id: str
    r"""Tenant ID"""
    environment_id: str
    r"""Environment ID"""
    intuit_signature: NotRequired[str]
    r"""QuickBooks webhook signature"""


class PostWebhooksQuickbooksTenantIDEnvironmentIDRequest(BaseModel):
    tenant_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Tenant ID"""

    environment_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Environment ID"""

    intuit_signature: Annotated[
        Optional[str],
        pydantic.Field(alias="intuit-signature"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""QuickBooks webhook signature"""
