"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 19d6a9ba5aab

from __future__ import annotations
from .dto_updatewalletrequest import (
    DtoUpdateWalletRequest,
    DtoUpdateWalletRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PutWalletsIDRequestTypedDict(TypedDict):
    id: str
    r"""Wallet ID"""
    body: DtoUpdateWalletRequestTypedDict
    r"""Update wallet request"""


class PutWalletsIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Wallet ID"""

    body: Annotated[
        DtoUpdateWalletRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Update wallet request"""
