"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 96c3ee1c7d26

from __future__ import annotations
from .dto_updatecouponrequest import (
    DtoUpdateCouponRequest,
    DtoUpdateCouponRequestTypedDict,
)
from flexprice.types import BaseModel
from flexprice.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class PutCouponsIDRequestTypedDict(TypedDict):
    id: str
    r"""Coupon ID"""
    body: DtoUpdateCouponRequestTypedDict
    r"""Coupon update request"""


class PutCouponsIDRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Coupon ID"""

    body: Annotated[
        DtoUpdateCouponRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Coupon update request"""
