"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7a2e877fdead

from __future__ import annotations
from typing import Literal


TypesSecretProvider = Literal[
    "flexprice",
    "stripe",
    "s3",
    "hubspot",
    "razorpay",
    "chargebee",
    "quickbooks",
    "nomod",
]
