"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e4996f92c01a

from __future__ import annotations
from typing import Literal


TypesAlertEntityType = Literal[
    "wallet",
    "feature",
]
