"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 6ecb14314f4a

from __future__ import annotations
from typing import Literal


TypesAlertState = Literal[
    "ok",
    "info",
    "warning",
    "in_alarm",
]
