"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d54621acbd23

from __future__ import annotations
from .types_addontype import TypesAddonType
from .types_filtercondition import TypesFilterCondition, TypesFilterConditionTypedDict
from .types_sortcondition import TypesSortCondition, TypesSortConditionTypedDict
from .types_status import TypesStatus
from flexprice.types import BaseModel
from typing import List, Literal, Optional
from typing_extensions import NotRequired, TypedDict


Order = Literal[
    "asc",
    "desc",
]


class TypesAddonFilterTypedDict(TypedDict):
    addon_ids: NotRequired[List[str]]
    addon_type: NotRequired[TypesAddonType]
    end_time: NotRequired[str]
    expand: NotRequired[str]
    filters: NotRequired[List[TypesFilterConditionTypedDict]]
    r"""filters allows complex filtering based on multiple fields"""
    limit: NotRequired[int]
    lookup_keys: NotRequired[List[str]]
    offset: NotRequired[int]
    order: NotRequired[Order]
    sort: NotRequired[List[TypesSortConditionTypedDict]]
    start_time: NotRequired[str]
    status: NotRequired[TypesStatus]


class TypesAddonFilter(BaseModel):
    addon_ids: Optional[List[str]] = None

    addon_type: Optional[TypesAddonType] = None

    end_time: Optional[str] = None

    expand: Optional[str] = None

    filters: Optional[List[TypesFilterCondition]] = None
    r"""filters allows complex filtering based on multiple fields"""

    limit: Optional[int] = None

    lookup_keys: Optional[List[str]] = None

    offset: Optional[int] = None

    order: Optional[Order] = None

    sort: Optional[List[TypesSortCondition]] = None

    start_time: Optional[str] = None

    status: Optional[TypesStatus] = None
