"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 2b0c55a86366

from __future__ import annotations
from typing import Literal


TypesFilterOperatorType = Literal[
    "eq",
    "contains",
    "gt",
    "lt",
    "in",
    "not_in",
    "before",
    "after",
]
