"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: a0d95d0c29ab

from __future__ import annotations
from typing import Literal


TypesScheduledTaskEntityType = Literal[
    "events",
    "invoice",
    "credit_topups",
]
