"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 741a96b4faba

from __future__ import annotations
from typing import Literal


TypesWalletStatus = Literal[
    "active",
    "frozen",
    "closed",
]
