"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 200db3b1879b

from __future__ import annotations
from typing import Literal


TypesS3EncryptionType = Literal[
    "AES256",
    "aws:kms",
    "aws:kms:dsse",
]
