"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4ed3b4dffc62

from __future__ import annotations
from typing import Literal


TypesWindowSize = Literal[
    "MINUTE",
    "15MIN",
    "30MIN",
    "HOUR",
    "3HOUR",
    "6HOUR",
    "12HOUR",
    "DAY",
    "WEEK",
    "MONTH",
]
